### ISSUE TITLE
Restore snapshots with the URL last played

### ISSUE THREAD

**Issue by saschaludwig** [mjcumming/wiim#116]
Could you please reopen #108?
It is still impossible to recall a scene where a URL was played when saving the scene. I tried with 1.0.22.
The status of the player still doesn't have the playing URL in it.
So the only solution I could see for this is configurable sources like in the above-mentioned linkplay2 integration and like mentioned earlier here #37

**Comment by mjcumming** [comment]
.23 should have this working now - test and let me know.

**Comment by saschaludwig** [comment]
Yes! Finally, that works now <3
Thanks a lot for that awesome fix

**Comment by saschaludwig** [comment]
I found a regression with the latest versions, when I try to restore the scene I get this error:

Failed to select sound mode 'Off': Invalid JSON response from https://192.168.42.132:443/httpapi.asp?command=EQOff: Expecting value: line 1 column 1 (char 0) (endpoint=https://192.168.42.132:443/httpapi.asp?command=EQOff)

Is that enough information or do you need more specific logs?

**Comment by saschaludwig** [comment]
Looks like it could be related to #108 and the restoration of the EQ, somehow that bit got lost.

**Comment by mjcumming** [comment]
I am not seeing this error in .58 - let me know if it fixes it for you.

**Comment by saschaludwig** [comment]
Sadly, it isn't fixed in .58 still the same error:

<img width="598" height="245" alt="Image" src="https://github.com/user-attachments/assets/1e87e38c-527b-4be4-b58d-f8ca00ab1a40" />

**Comment by saschaludwig** [comment]
Should I open a new issue, or do you want to reopen this one?

**Comment by saschaludwig** [comment]
This is when I get the URL manually.
It returns "unknown command%"

```
❯ curl http://192.168.42.132/httpapi.asp\?command\=EQOff -vv
*   Trying 192.168.42.132:80...
* Connected to 192.168.42.132 (192.168.42.132) port 80
> GET /httpapi.asp?command=EQOff HTTP/1.1
> Host: 192.168.42.132
> User-Agent: curl/8.7.1
> Accept: */*
>
* Request completely sent off
* HTTP 1.0, assume close after body
< HTTP/1.0 200 OK
< Date: Fri Feb 13 00:00:30 2026
< Server: GoAhead-Webs
< Pragma: no-cache
< Cache-Control: no-cache
< Content-type: text/html
<
* Closing connection
unknown command%
```

**Comment by saschaludwig** [comment]
You previously fixed that exact same problem we have now, here: https://github.com/mjcumming/wiim/issues/108#issue-3621691145

**Comment by mjcumming** [comment]
Thanks for reporting this and for the details.
The EQOff failure has been fixed. Some devices (including Arylic UP2STREAM) return plain text "unknown command" instead of JSON for EQOff, which broke scene restoration when the saved sound mode was "Off". The library now treats that response as success instead of raising an error, so scene restoration should no longer fail on those devices.
The fix is in pywiim. After the next release, update your WiiM integration (which uses pywiim) and try restoring your scene again. If anything still fails, please share the new error message and we can look into it.
For URL-based streams: media_content_id should be in the snapshot when you save, and the integration should use it to call play_url() when restoring. That behavior was added in v1.0.23. If you still see problems with URL restoration after this fix, tell us what you’re seeing and we can trace it.

**Comment by saschaludwig** [comment]
I will try that on the next reboot of my system. Thanks for your superfast response! That is greatly appreciated!

**Comment by saschaludwig** [comment]
Tested with v1.0.62
I'm afraid, it's still the same problem:
`Failed to select sound mode 'Off': Invalid JSON response from https://192.168.42.132:443/httpapi.asp?command=EQOff: Expecting value: line 1 column 1 (char 0) (endpoint=https://192.168.42.132:443/httpapi.asp?command=EQOff)`

**Comment by mjcumming** [comment]
hm, that should have been fixed - in the HA device page - what version of pywiim is installed? i think we call it serial number or something

**Comment by saschaludwig** [comment]
I took a look at my wiim's version.py and found that in it:
`REQUIRED_PYWIIM_VERSION = "2.1.81"`

And that is also what I get from the device page:
<img width="337" height="369" alt="Image" src="https://github.com/user-attachments/assets/f48f42ba-fe73-4ffd-a530-1b6ab3301343" />

**Comment by mjcumming** [comment]
ok, try the current wiim release - but i am not optimistic we got this fixed - let me know.

**Comment by saschaludwig** [comment]
It's working again. Thank you very much!
