### ISSUE TITLE
[Bug]: State remains idle (Spotify)

### ISSUE THREAD

**Issue by shpongledsummer** [mjcumming/wiim#122]
### Pre-submission Checklist

- [x] I have searched existing issues and this is not a duplicate
- [x] I am using the latest version of the WiiM integration
- [x] I have enabled debug logging and included relevant logs below
- [x] I have included the integration diagnostics

### Integration Version

v1.0.27

### Home Assistant Version

2025.11.3

### WiiM Device Model

Other LinkPlay device

### Bug Description

After updating to the latest version the issues from number #103 are still happening. I am also seeing new problems like volume control for an active player not working at all. I hope to find time next weekend to create separate reports for the new issues. Version 0.28 is still the only version that works correctly with my older Audio Pro devices. Since support for the MK2 devices was added the older models I use seem to have lost compatibility. These older models work very differently even though they are also branded Audio Pro and they can be controlled with simple http commands.

Spotify playback does not update the state. Bluetooth still updates the state correctly.

### Steps to Reproduce

1. Play something (tested with regular Spotify and Symfonium / Music Assitant via DLNA)
2. state does not update and shows "idle"

### Configuration

```yaml

```

### Integration Diagnostics

[wiim-01JXG8D4DS8JRMA21WPYD0EBZT-Mandaloffice-8b1c529f46833e05816f5759ccef7a58 (4).json](https://github.com/user-attachments/files/23771760/wiim-01JXG8D4DS8JRMA21WPYD0EBZT-Mandaloffice-8b1c529f46833e05816f5759ccef7a58.4.json)

### Debug Logs

```text
Debug logging did not show much, but this part looks important. The integration uses a source value with uppercase letters. Maybe always using lowercase would avoid this?

Logger: custom_components.wiim.media_player
Source: custom_components/wiim/media_player.py:628

Source 'Idle' not found in available_sources or input_list, using lowercase version: 'idle'




Other logged issues:

Logger: custom_components.wiim.diagnostics
Quelle: custom_components/wiim/diagnostics.py:277
Integration: WiiM (Dokumentation, Probleme)
Erstmals aufgetreten: 13:44:31 (1 Vorkommnis)
Zuletzt protokolliert: 13:44:31

Failed to generate device diagnostics
Traceback (most recent call last):
  File "/config/custom_components/wiim/diagnostics.py", line 277, in async_get_device_diagnostics
    has_upnp_client = coordinator.upnp_client is not None
                      ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'WiiMCoordinator' object has no attribute 'upnp_client'



Dieser Fehler stammt von einer benutzerdefinierten Integration

Logger: pywiim.player.properties
Quelle: custom_components/wiim/select.py:145
Integration: WiiM (Dokumentation, Probleme)
Erstmals aufgetreten: 13:32:22 (1004 Vorkommnisse)
Zuletzt protokolliert: 13:54:19

Unknown audio output mode 7 (hardware=7, source=0) for device 192.168.178.52 (model=WiiM_Amp_Ultra)
```

### Installation Method

HACS

**Comment by mjcumming** [comment]
.28 should fix the playing and hardware outputs - for other issues please do on issue per probelm so we can track better.

**Comment by shpongledsummer** [comment]
Thanks for the quick update. I just tested the latest version:

- When the speaker is grouped, the state still doesn’t work. Both the master and its slaves show as “idle”
- However, the state now works correctly when the speaker is NOT part of a master/slave group

Just a note: I’m still not entirely sure how to provide meaningful debug logs for this. I enabled “debug mode” via the action, but I can’t see anything useful in the logs, aside from the usual issues with the media images not loading. I’ve attached the device diagnostics again in case it helps. Let me know if there’s a way to gather more meaningful information.

[wiim-01JXG8D4DS8JRMA21WPYD0EBZT-Mandaloffice-8b1c529f46833e05816f5759ccef7a58 (5).json](https://github.com/user-attachments/files/23822941/wiim-01JXG8D4DS8JRMA21WPYD0EBZT-Mandaloffice-8b1c529f46833e05816f5759ccef7a58.5.json)

**Comment by mjcumming** [comment]
No likely fixed in .31 release - this is complicated to solve given the combination of players you have (old audio pro). Try the update and let me know.

**Comment by shpongledsummer** [comment]
I tested version **0.35**, and it now correctly shows the state as "playing" with all my sources (including Spotify). There are still several other issues that keep me from switching from that old 0.28 release, but this particular problem appears to be resolved.

However, there still seems to be a lowercase related issue:

Logger: custom_components.wiim.media_player
Source: custom_components/wiim/media_player.py:657
Integration: WiiM (Documentation, Issues)
First occurred: 12:44:23 (3 occurrences)
Last logged: 12:49:54

Source 'Idle' not found in available_sources or input_list, using lowercase version: 'idle'
