### ISSUE TITLE
[Bug]: Bluetooth output sensor not working anymore

### ISSUE THREAD

**Issue by DonaldGermany** [mjcumming/wiim#123]
### Pre-submission Checklist

- [x] I have searched existing issues and this is not a duplicate
- [x] I am using the latest version of the WiiM integration
- [x] I have enabled debug logging and included relevant logs below
- [x] I have included the integration diagnostics

### Integration Version

v1.0.28

### Home Assistant Version

latest

### WiiM Device Model

WiiM Pro

### Bug Description

I noticed that the bluetooth output sensor is not working since the new major 1.0 was released, had to go back to Version 0.2.28 to make it work again. 

### Steps to Reproduce

Connect a bluetooth device to Wiim device and monitor bluetooth output sensor

### Configuration

```yaml

```

### Integration Diagnostics

"home_assistant": {
    "installation_type": "Home Assistant OS",
    "version": "2025.11.3",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.13.9",
    "docker": true,
    "arch": "x86_64",
    "timezone": "Europe/Berlin",
    "os_name": "Linux",
    "os_version": "6.12.51-haos",
    "container_arch": "amd64",
    "supervisor": "2025.11.5",
    "host_os": "Home Assistant OS 16.3",
    "docker_version": "28.3.3",
    "chassis": "vm",
    "run_as_root": true

 "integration_manifest": {
    "domain": "wiim",
    "name": "WiiM",
    "codeowners": [
      "mjcumming"
    ],
    "config_flow": true,
    "dependencies": [
      "http"
    ],
    "documentation": "https://github.com/mjcumming/wiim",
    "integration_type": "device",
    "iot_class": "local_polling",
    "issue_tracker": "https://github.com/mjcumming/wiim/issues",
    "quality_scale": "silver",
    "requirements": [],
    "ssdp": [
      {
        "manufacturer": "WiiM",
        "st": "upnp:rootdevice"
      },
      {
        "manufacturer": "LinkPlay",
        "st": "upnp:rootdevice"
      },
      {
        "manufacturer": "WiiM",
        "device_type": "urn:schemas-upnp-org:device:MediaRenderer:1"
      },
      {
        "manufacturer": "LinkPlay",
        "device_type": "urn:schemas-upnp-org:device:MediaRenderer:1"
      },
      {
        "st": "urn:schemas-upnp-org:service:AVTransport:1"
      },
      {
        "st": "urn:schemas-upnp-org:service:RenderingControl:1"
      },
      {
        "st": "urn:schemas-upnp-org:service:ConnectionManager:1"
      }
    ],
    "version": "0.2.28",
    "zeroconf": [
      {
        "type": "_linkplay._tcp.local."
      }
    ],
    "is_built_in": false,
    "overwrites_built_in": false
  },
  "setup_times": {
    "null": {
      "setup": 1.9900035113096237e-05
    },
    "01K0PG7KQT5JVJB8HD3MDAKC4T": {
      "wait_import_platforms": -3.005253881914541,
      "config_entry_setup": 5.720827849116176
    }
  },
  "data": {
    "entry_data": {
      "endpoint": "https://192.168.1.95:443",
      "host": "**REDACTED**"
    },
    "entry_options": {},
    "integration_info": {
      "total_speakers": 1,
      "available_speakers": 1,
      "roles": {
        "solo": 1,
        "master": 0,
        "slave": 0
      },
      "models": [
        "WiiM_Pro_with_gc4a"
      ]
    },
    "coordinator": {
      "update_interval": 5.0,
      "last_update_success": true,
      "last_update": null,
      "data_keys": [
        "status_model",
        "device_model",
        "multiroom",
        "metadata_model",
        "metadata",
        "eq_model",
        "eq",
        "presets",
        "role",
        "polling_metrics",
        "polling",
        "audio_output",
        "bt_pair_status",
        "bt_history"
      ],
      "client_host": "xxxxxxxx"
    },
    "speaker_basic": {
      "name": "WiiM Pro-C9BE",
      "model": "WiiM_Pro_with_gc4a",
      "firmware": "Linkplay.4.8.731953",
      "role": "solo",
      "available": true,
      "group_members_count": 0
    }
  },
  "issues": []
}

### Debug Logs

```text
N/A
```

### Installation Method

HACS

**Comment by mjcumming** [comment]
.29 should have this fixed - let me know.

**Comment by DonaldGermany** [comment]
No didn't fix it. Below are the debug logs. Only hardware outputs are changed to bluetooth (but new state is unknown), but it did that in the previous version already. However, the Bluetooth Out Sensor is not updated. 

[36m2025-11-27 18:36:00.082 DEBUG (MainThread) [pywiim.api.parser] 🎵 API PARSER: Setting data['position'] = 0[0m
[36m2025-11-27 18:36:00.082 DEBUG (MainThread) [pywiim.api.parser] 🎵 Position from API: 0 seconds (source: -1, raw_value: 0)[0m
[36m2025-11-27 18:36:00.082 DEBUG (MainThread) [pywiim.api.parser] Mode -1 maps to 'unknown' (not a valid source), keeping source 'missing'[0m
[36m2025-11-27 18:36:00.083 DEBUG (MainThread) [pywiim.player.groupops] Device info cached for xxxxxxxx - checking role via get_device_group_info()[0m
[36m2025-11-27 18:36:00.083 DEBUG (MainThread) [pywiim.api.base] HTTP start host=xxxxxxxx attempt=1 GET https://xxxxxxxx:443/httpapi.asp?command=getStatusEx[0m
[36m2025-11-27 18:36:00.200 DEBUG (MainThread) [pywiim.api.base] HTTP done host=xxxxxxxx status=200 117.4ms GET https://xxxxxxxx:443/httpapi.asp?command=getStatusEx[0m
[36m2025-11-27 18:36:00.201 DEBUG (MainThread) [pywiim.api.base] HTTP start host=xxxxxxxx attempt=1 GET https://xxxxxxxx:443/httpapi.asp?command=getStatusEx[0m
[36m2025-11-27 18:36:00.317 DEBUG (MainThread) [pywiim.api.base] HTTP done host=xxxxxxxx status=200 115.9ms GET https://xxxxxxxx:443/httpapi.asp?command=getStatusEx[0m
[36m2025-11-27 18:36:00.317 DEBUG (MainThread) [pywiim.api.base] HTTP start host=xxxxxxxx attempt=1 GET https://xxxxxxxx:443/httpapi.asp?command=multiroom:getSlaveList[0m
[36m2025-11-27 18:36:00.392 DEBUG (MainThread) [pywiim.api.base] HTTP done host=xxxxxxxx status=200 74.9ms GET https://xxxxxxxx:443/httpapi.asp?command=multiroom:getSlaveList[0m
[36m2025-11-27 18:36:00.393 DEBUG (MainThread) [pywiim.api.group] get_slaves() raw response: {'slaves': 0, 'wmrm_version': '4.3', 'surround': 0}[0m
[36m2025-11-27 18:36:00.393 DEBUG (MainThread) [pywiim.api.group] get_slaves() extracted data: 0 (type: int)[0m
[36m2025-11-27 18:36:00.393 DEBUG (MainThread) [pywiim.api.group] get_slaves() data is not a list, returning empty[0m
[36m2025-11-27 18:36:00.393 DEBUG (MainThread) [pywiim.api.group] get_device_group_info: Detected SOLO (get_slaves() returned empty)[0m
[36m2025-11-27 18:36:00.393 DEBUG (MainThread) [custom_components.wiim.media_player] [WiiM Pro-C9BE] Coordinator update (state=idle, raw_pos=0, raw_dur=None)[0m
[36m2025-11-27 18:36:00.393 DEBUG (MainThread) [custom_components.wiim.media_player] [WiiM Pro-C9BE] Published position=None (ts=None) duration=None[0m
[36m2025-11-27 18:36:00.394 DEBUG (MainThread) [pywiim.player.properties] Parsed plm_support: value=0x700016 (0x700016), detected inputs (before filtering): ['bluetooth', 'usb'], all set bits: bit2 (bit 1), bit3 (bit 2), bit5 (bit 4)[0m
[36m2025-11-27 18:36:00.394 DEBUG (MainThread) [pywiim.player.properties] After device-specific filtering: ['bluetooth'][0m
[36m2025-11-27 18:36:00.394 DEBUG (MainThread) [pywiim.player.properties] input_list not available or empty after filtering, augmenting with device capability database for WiiM_Pro_with_gc4a (vendor: wiim)[0m
[36m2025-11-27 18:36:00.396 DEBUG (MainThread) [custom_components.wiim.coordinator] Finished fetching WiiM xxxxxxxx data in 0.402 seconds (success: True)[0m
[36m2025-11-27 18:36:00.396 DEBUG (MainThread) [custom_components.wiim.media_player] [WiiM Pro-C9BE] Coordinator update (state=idle, raw_pos=0, raw_dur=None)[0m
[36m2025-11-27 18:36:00.396 DEBUG (MainThread) [custom_components.wiim.media_player] [WiiM Pro-C9BE] Published position=None (ts=None) duration=None[0m
[36m2025-11-27 18:36:00.396 DEBUG (MainThread) [pywiim.player.properties] Parsed plm_support: value=0x700016 (0x700016), detected inputs (before filtering): ['bluetooth', 'usb'], all set bits: bit2 (bit 1), bit3 (bit 2), bit5 (bit 4)[0m
[36m2025-11-27 18:36:00.396 DEBUG (MainThread) [pywiim.player.properties] After device-specific filtering: ['bluetooth'][0m
[36m2025-11-27 18:36:00.396 DEBUG (MainThread) [pywiim.player.properties] input_list not available or empty after filtering, augmenting with device capability database for WiiM_Pro_with_gc4a (vendor: wiim)[0m
[36m2025-11-27 18:36:04.994 DEBUG (MainThread) [pywiim.api.base] HTTP start host=xxxxxxxx attempt=1 GET https://xxxxxxxx:443/httpapi.asp?command=getPlayerStatusEx[0m
[36m2025-11-27 18:36:05.097 DEBUG (MainThread) [pywiim.api.base] HTTP done host=xxxxxxxx status=200 103.4ms GET https://xxxxxxxx:443/httpapi.asp?command=getPlayerStatusEx[0m
[36m2025-11-27 18:36:05.098 DEBUG (MainThread) [pywiim.api.parser] 🎵 Position value 0 appears to be in milliseconds, converting to seconds: 0 seconds (source: -1)[0m
[36m2025-11-27 18:36:05.098 DEBUG (MainThread) [pywiim.api.parser] 🎵 API PARSER: Setting data['position'] = 0[0m
[36m2025-11-27 18:36:05.098 DEBUG (MainThread) [pywiim.api.parser] 🎵 Position from API: 0 seconds (source: -1, raw_value: 0)[0m
[36m2025-11-27 18:36:05.098 DEBUG (MainThread) [pywiim.api.parser] Mode -1 maps to 'unknown' (not a valid source), keeping source 'missing'[0m
[36m2025-11-27 18:36:05.098 DEBUG (MainThread) [pywiim.player.groupops] Device info cached for xxxxxxxx - checking role via get_device_group_info()[0m
[36m2025-11-27 18:36:05.099 DEBUG (MainThread) [pywiim.api.base] HTTP start host=xxxxxxxx attempt=1 GET https://xxxxxxxx:443/httpapi.asp?command=getStatusEx[0m
[36m2025-11-27 18:36:05.219 DEBUG (MainThread) [pywiim.api.base] HTTP done host=xxxxxxxx status=200 120.0ms GET https://xxxxxxxx:443/httpapi.asp?command=getStatusEx[0m
[36m2025-11-27 18:36:05.219 DEBUG (MainThread) [pywiim.api.base] HTTP start host=xxxxxxxx attempt=1 GET https://xxxxxxxx:443/httpapi.asp?command=getStatusEx[0m
[36m2025-11-27 18:36:05.337 DEBUG (MainThread) [pywiim.api.base] HTTP done host=xxxxxxxx status=200 117.5ms GET https://xxxxxxxx:443/httpapi.asp?command=getStatusEx[0m
[36m2025-11-27 18:36:05.338 DEBUG (MainThread) [pywiim.api.base] HTTP start host=xxxxxxxx attempt=1 GET https://xxxxxxxx:443/httpapi.asp?command=multiroom:getSlaveList[0m
[36m2025-11-27 18:36:05.412 DEBUG (MainThread) [pywiim.api.base] HTTP done host=xxxxxxxx status=200 74.1ms GET https://xxxxxxxx:443/httpapi.asp?command=multiroom:getSlaveList[0m
[36m2025-11-27 18:36:05.412 DEBUG (MainThread) [pywiim.api.group] get_slaves() raw response: {'slaves': 0, 'wmrm_version': '4.3', 'surround': 0}[0m
[36m2025-11-27 18:36:05.412 DEBUG (MainThread) [pywiim.api.group] get_slaves() extracted data: 0 (type: int)[0m
[36m2025-11-27 18:36:05.412 DEBUG (MainThread) [pywiim.api.group] get_slaves() data is not a list, returning empty[0m
[36m2025-11-27 18:36:05.412 DEBUG (MainThread) [pywiim.api.group] get_device_group_info: Detected SOLO (get_slaves() returned empty)[0m
[36m2025-11-27 18:36:05.412 DEBUG (MainThread) [custom_components.wiim.media_player] [WiiM Pro-C9BE] Coordinator update (state=idle, raw_pos=0, raw_dur=None)[0m
[36m2025-11-27 18:36:05.412 DEBUG (MainThread) [custom_components.wiim.media_player] [WiiM Pro-C9BE] Published position=None (ts=None) duration=None[0m
[36m2025-11-27 18:36:05.412 DEBUG (MainThread) [pywiim.player.properties] Parsed plm_support: value=0x700016 (0x700016), detected inputs (before filtering): ['bluetooth', 'usb'], all set bits: bit2 (bit 1), bit3 (bit 2), bit5 (bit 4)[0m
[36m2025-11-27 18:36:05.412 DEBUG (MainThread) [pywiim.player.properties] After device-specific filtering: ['bluetooth'][0m
[36m2025-11-27 18:36:05.413 DEBUG (MainThread) [pywiim.player.properties] input_list not available or empty after filtering, augmenting with device capability database for WiiM_Pro_with_gc4a (vendor: wiim)[0m
[36m2025-11-27 18:36:05.413 DEBUG (MainThread) [custom_components.wiim.coordinator] Finished fetching WiiM xxxxxxxx data in 0.420 seconds (success: True)[0m
[36m2025-11-27 18:36:05.413 DEBUG (MainThread) [custom_components.wiim.media_player] [WiiM Pro-C9BE] Coordinator update (state=idle, raw_pos=0, raw_dur=None)[0m
[36m2025-11-27 18:36:05.413 DEBUG (MainThread) [custom_components.wiim.media_player] [WiiM Pro-C9BE] Published position=None (ts=None) duration=None[0m
[36m2025-11-27 18:36:05.413 DEBUG (MainThread) [pywiim.player.properties] Parsed plm_support: value=0x700016 (0x700016), detected inputs (before filtering): ['bluetooth', 'usb'], all set bits: bit2 (bit 1), bit3 (bit 2), bit5 (bit 4)[0m
[36m2025-11-27 18:36:05.414 DEBUG (MainThread) [pywiim.player.properties] After device-specific filtering: ['bluetooth'][0m
[36m2025-11-27 18:36:05.414 DEBUG (MainThread) [pywiim.player.properties] input_list not available or empty after filtering, augmenting with device capability database for WiiM_Pro_with_gc4a (vendor: wiim)[0m
[36m2025-11-27 18:36:09.994 DEBUG (MainThread) [pywiim.api.base] HTTP start host=xxxxxxxx attempt=1 GET https://xxxxxxxx:443/httpapi.asp?command=getPlayerStatusEx[0m
[36m2025-11-27 18:36:10.084 DEBUG (MainThread) [pywiim.api.base] HTTP done host=xxxxxxxx status=200 90.7ms GET https://xxxxxxxx:443/httpapi.asp?command=getPlayerStatusEx[0m
[36m2025-11-27 18:36:10.085 DEBUG (MainThread) [pywiim.api.parser] 🎵 Position value 0 appears to be in milliseconds, converting to seconds: 0 seconds (source: -1)[0m
[36m2025-11-27 18:36:10.085 DEBUG (MainThread) [pywiim.api.parser] 🎵 API PARSER: Setting data['position'] = 0[0m
[36m2025-11-27 18:36:10.085 DEBUG (MainThread) [pywiim.api.parser] 🎵 Position from API: 0 seconds (source: -1, raw_value: 0)[0m
[36m2025-11-27 18:36:10.085 DEBUG (MainThread) [pywiim.api.parser] Mode -1 maps to 'unknown' (not a valid source), keeping source 'missing'[0m
[36m2025-11-27 18:36:10.085 DEBUG (MainThread) [pywiim.player.groupops] Device info cached for xxxxxxxx - checking role via get_device_group_info()[0m
[36m2025-11-27 18:36:10.085 DEBUG (MainThread) [pywiim.api.base] HTTP start host=xxxxxxxx attempt=1 GET https://xxxxxxxx:443/httpapi.asp?command=getStatusEx[0m
[36m2025-11-27 18:36:10.207 DEBUG (MainThread) [pywiim.api.base] HTTP done host=xxxxxxxx status=200 122.1ms GET https://xxxxxxxx:443/httpapi.asp?command=getStatusEx[0m
[36m2025-11-27 18:36:10.208 DEBUG (MainThread) [pywiim.api.base] HTTP start host=xxxxxxxx attempt=1 GET https://xxxxxxxx:443/httpapi.asp?command=getStatusEx[0m
[36m2025-11-27 18:36:10.324 DEBUG (MainThread) [pywiim.api.base] HTTP done host=xxxxxxxx status=200 116.3ms GET https://xxxxxxxx:443/httpapi.asp?command=getStatusEx[0m
[36m2025-11-27 18:36:10.325 DEBUG (MainThread) [pywiim.api.base] HTTP start host=xxxxxxxx attempt=1 GET https://xxxxxxxx:443/httpapi.asp?command=multiroom:getSlaveList[0m
[36m2025-11-27 18:36:10.399 DEBUG (MainThread) [pywiim.api.base] HTTP done host=xxxxxxxx status=200 73.9ms GET https://xxxxxxxx:443/httpapi.asp?command=multiroom:getSlaveList[0m
[36m2025-11-27 18:36:10.399 DEBUG (MainThread) [pywiim.api.group] get_slaves() raw response: {'slaves': 0, 'wmrm_version': '4.3', 'surround': 0}[0m
[36m2025-11-27 18:36:10.399 DEBUG (MainThread) [pywiim.api.group] get_slaves() extracted data: 0 (type: int)[0m
[36m2025-11-27 18:36:10.399 DEBUG (MainThread) [pywiim.api.group] get_slaves() data is not a list, returning empty[0m
[36m2025-11-27 18:36:10.399 DEBUG (MainThread) [pywiim.api.group] get_device_group_info: Detected SOLO (get_slaves() returned empty)[0m
[36m2025-11-27 18:36:10.400 DEBUG (MainThread) [custom_components.wiim.media_player] [WiiM Pro-C9BE] Coordinator update (state=idle, raw_pos=0, raw_dur=None)[0m
[36m2025-11-27 18:36:10.400 DEBUG (MainThread) [custom_components.wiim.media_player] [WiiM Pro-C9BE] Published position=None (ts=None) duration=None[0m
[36m2025-11-27 18:36:10.400 DEBUG (MainThread) [pywiim.player.properties] Parsed plm_support: value=0x700016 (0x700016), detected inputs (before filtering): ['bluetooth', 'usb'], all set bits: bit2 (bit 1), bit3 (bit 2), bit5 (bit 4)[0m
[36m2025-11-27 18:36:10.400 DEBUG (MainThread) [pywiim.player.properties] After device-specific filtering: ['bluetooth'][0m
[36m2025-11-27 18:36:10.400 DEBUG (MainThread) [pywiim.player.properties] input_list not available or empty after filtering, augmenting with device capability database for WiiM_Pro_with_gc4a (vendor: wiim)[0m
[36m2025-11-27 18:36:10.401 DEBUG (MainThread) [custom_components.wiim.coordinator] Finished fetching WiiM xxxxxxxx data in 0.407 seconds (success: True)[0m
[36m2025-11-27 18:36:10.401 DEBUG (MainThread) [custom_components.wiim.media_player] [WiiM Pro-C9BE] Coordinator update (state=idle, raw_pos=0, raw_dur=None)[0m
[36m2025-11-27 18:36:10.401 DEBUG (MainThread) [custom_components.wiim.media_player] [WiiM Pro-C9BE] Published position=None (ts=None) duration=None[0m
[36m2025-11-27 18:36:10.401 DEBUG (MainThread) [pywiim.player.properties] Parsed plm_support: value=0x700016 (0x700016), detected inputs (before filtering): ['bluetooth', 'usb'], all set bits: bit2 (bit 1), bit3 (bit 2), bit5 (bit 4)[0m
[36m2025-11-27 18:36:10.401 DEBUG (MainThread) [pywiim.player.properties] After device-specific filtering: ['bluetooth'][0m
[36m2025-11-27 18:36:10.402 DEBUG (MainThread) [pywiim.player.properties] input_list not available or empty after filtering, augmenting with device capability database for WiiM_Pro_with_gc4a (vendor: wiim)[0m
[36m2025-11-27 18:36:15.015 DEBUG (MainThread) [pywiim.api.base] HTTP start host=xxxxxxxx attempt=1 GET https://xxxxxxxx:443/httpapi.asp?command=getPlayerStatusEx[0m
[36m2025-11-27 18:36:15.106 DEBUG (MainThread) [pywiim.api.base] HTTP done host=xxxxxxxx status=200 90.9ms GET https://xxxxxxxx:443/httpapi.asp?command=getPlayerStatusEx[0m
[36m2025-11-27 18:36:15.106 DEBUG (MainThread) [pywiim.api.parser] 🎵 Position value 0 appears to be in milliseconds, converting to seconds: 0 seconds (source: -1)[0m
[36m2025-11-27 18:36:15.106 DEBUG (MainThread) [pywiim.api.parser] 🎵 API PARSER: Setting data['position'] = 0[0m
[36m2025-11-27 18:36:15.106 DEBUG (MainThread) [pywiim.api.parser] 🎵 Position from API: 0 seconds (source: -1, raw_value: 0)[0m
[36m2025-11-27 18:36:15.106 DEBUG (MainThread) [pywiim.api.parser] Mode -1 maps to 'unknown' (not a valid source), keeping source 'missing'[0m
[36m2025-11-27 18:36:15.107 DEBUG (MainThread) [pywiim.player.groupops] Device info cached for xxxxxxxx - checking role via get_device_group_info()[0m
[36m2025-11-27 18:36:15.107 DEBUG (MainThread) [pywiim.api.base] HTTP start host=xxxxxxxx attempt=1 GET https://xxxxxxxx:443/httpapi.asp?command=getStatusEx[0m
[36m2025-11-27 18:36:15.231 DEBUG (MainThread) [pywiim.api.base] HTTP done host=xxxxxxxx status=200 124.5ms GET https://xxxxxxxx:443/httpapi.asp?command=getStatusEx[0m
[36m2025-11-27 18:36:15.232 DEBUG (MainThread) [pywiim.api.base] HTTP start host=xxxxxxxx attempt=1 GET https://xxxxxxxx:443/httpapi.asp?command=getStatusEx[0m
[36m2025-11-27 18:36:15.355 DEBUG (MainThread) [pywiim.api.base] HTTP done host=xxxxxxxx status=200 122.5ms GET https://xxxxxxxx:443/httpapi.asp?command=getStatusEx[0m
[36m2025-11-27 18:36:15.356 DEBUG (MainThread) [pywiim.api.base] HTTP start host=xxxxxxxx attempt=1 GET https://xxxxxxxx:443/httpapi.asp?command=multiroom:getSlaveList[0m
[36m2025-11-27 18:36:15.434 DEBUG (MainThread) [pywiim.api.base] HTTP done host=xxxxxxxx status=200 77.8ms GET https://xxxxxxxx:443/httpapi.asp?command=multiroom:getSlaveList[0m
[36m2025-11-27 18:36:15.434 DEBUG (MainThread) [pywiim.api.group] get_slaves() raw response: {'slaves': 0, 'wmrm_version': '4.3', 'surround': 0}[0m
[36m2025-11-27 18:36:15.434 DEBUG (MainThread) [pywiim.api.group] get_slaves() extracted data: 0 (type: int)[0m
[36m2025-11-27 18:36:15.434 DEBUG (MainThread) [pywiim.api.group] get_slaves() data is not a list, returning empty[0m
[36m2025-11-27 18:36:15.434 DEBUG (MainThread) [pywiim.api.group] get_device_group_info: Detected SOLO (get_slaves() returned empty)[0m
[36m2025-11-27 18:36:15.434 DEBUG (MainThread) [custom_components.wiim.media_player] [WiiM Pro-C9BE] Coordinator update (state=idle, raw_pos=0, raw_dur=None)[0m
[36m2025-11-27 18:36:15.434 DEBUG (MainThread) [custom_components.wiim.media_player] [WiiM Pro-C9BE] Published position=None (ts=None) duration=None[0m
[36m2025-11-27 18:36:15.434 DEBUG (MainThread) [pywiim.player.properties] Parsed plm_support: value=0x700016 (0x700016), detected inputs (before filtering): ['bluetooth', 'usb'], all set bits: bit2 (bit 1), bit3 (bit 2), bit5 (bit 4)[0m
[36m2025-11-27 18:36:15.434 DEBUG (MainThread) [pywiim.player.properties] After device-specific filtering: ['bluetooth'][0m
[36m2025-11-27 18:36:15.434 DEBUG (MainThread) [pywiim.player.properties] input_list not available or empty after filtering, augmenting with device capability database for WiiM_Pro_with_gc4a (vendor: wiim)[0m
[36m2025-11-27 18:36:15.435 DEBUG (MainThread) [custom_components.wiim.coordinator] Finished fetching WiiM xxxxxxxx data in 0.421 seconds (success: True)[0m
[36m2025-11-27 18:36:15.435 DEBUG (MainThread) [custom_components.wiim.media_player] [WiiM Pro-C9BE] Coordinator update (state=idle, raw_pos=0, raw_dur=None)[0m
[36m2025-11-27 18:36:15.435 DEBUG (MainThread) [custom_components.wiim.media_player] [WiiM Pro-C9BE] Published position=None (ts=None) duration=None[0m
[36m2025-11-27 18:36:15.435 DEBUG (MainThread) [pywiim.player.properties] Parsed plm_support: value=0x700016 (0x700016), detected inputs (before filtering): ['bluetooth', 'usb'], all set bits: bit2 (bit 1), bit3 (bit 2), bit5 (bit 4)[0m
[36m2025-11-27 18:36:15.435 DEBUG (MainThread) [pywiim.player.properties] After device-specific filtering: ['bluetooth'][0m
[36m2025-11-27 18:36:15.435 DEBUG (MainThread) [pywiim.player.properties] input_list not available or empty after filtering, augmenting with device capability database for WiiM_Pro_with_gc4a (vendor: wiim)[0m

**Comment by mjcumming** [comment]
.38 should fix this, alternatively using output_mode might be better

`> condition: state
> entity_id: select.wiim_pro_audio_output_mode
> state: "BT:"  # matches any Bluetooth device
> match: substring
>`

**Comment by DonaldGermany** [comment]
.38 didn't fix the bluethooth out sensor entidy. The output_mode is working now but takes about 1 min to update. The bluetooth sensor was about 10sec. As I'm using this as trigger to start the music the bluetooth sensor in pre 1.00 version is still working better for me.
