### ISSUE TITLE
[Bug]: Integration discovering Samsung TV, Sonos (S1) and Arylic as WIIM devices.

### ISSUE THREAD

**Issue by alexruffell** [mjcumming/wiim#141]
### Pre-submission Checklist

- [x] I have searched existing issues and this is not a duplicate
- [x] I am using the latest version of the WiiM integration
- [x] I have enabled debug logging and included relevant logs below
- [x] I have included the integration diagnostics

### Integration Version

1.0.33

### Home Assistant Version

2025.12.0b5

### Primary WiiM Device Model

Unknown/Multiple devices

### Primary Device Name

n/a

### Is this device part of a group?

No - device is standalone

### Grouped Devices Details

n/a

### Bug Description

I installed the WIIM integration a couple days ago. It discovered all 3 my WIIM devices, and an Arylic streamer which I was expecting as WIIM's app also discovers it.

What surprised me what that the last Sonos S1 One standing was discovered but fails to be added... but it keeps trying. Later in the day, also a Samsung TV got stuck in the same loop as it too can't be added. I disabled the 2 devices to stop the loop.

Below you see one (Sonos) that was disabled as it was added but kept reinitializing, and the other (Samsung TV) I then just ignored.

<img width="808" height="786" alt="Image" src="https://github.com/user-attachments/assets/e3dfad26-bc54-4f15-95ac-cc8c66ec5725" />

Here I re-enabled the Sonos, and this is the error it keeps showing on and off:

<img width="777" height="769" alt="Image" src="https://github.com/user-attachments/assets/4d3a4266-429b-49d3-82d2-f9c8b9460049" />

### Steps to Reproduce

1. Wait for devices to be discovered by the WIIM integration.
2. When device fails to be added - I tried even though they should not even be found - disable it to stop the attempts.

I have many more media devices but these are the only two that were causing the issue.

### Configuration

```yaml
Configuration of what?
```

### Integration Diagnostics

As far as I know I must be able to add the device to download the diagnostic. The issue is related to 2 devices that are found but cannot, and should not, be added.

### Debug Logs

```text
n/a
```

### Installation Method

HACS

**Comment by mjcumming** [comment]
Great info, Thanks. .32 release should solve this.

**Comment by alexruffell** [comment]
The first version I used was .32 and the screenshot of the error was with .33 so it would seem that the issue was not resolved. Is there any other information I can provide to assist ?

**Comment by alexruffell** [comment]
@mjcumming Even after updating to 1.0.36, thus including the other ".32" library update (going off memory), I still have the issue with WIIM discovering Sonos One (old S1), Samsung TV, and now also on of my 3 (the oldest one) Onkyo AV Receivers.

Please let me know if you need anything from me to help troubleshoot.

![Image](https://github.com/user-attachments/assets/4a75cd63-9d1f-40e3-9c8a-7275ab32f089)

**Comment by mjcumming** [comment]
The latest release should fix this. Let me know if not.

**Comment by alexruffell** [comment]
@mjcumming Unfortunately, even after full reboots, the 3 devices are still there waiting to be added by the WIIM integration.

**Comment by tmeuze** [comment]
Hello from the present. This behavior still occurs for me, recognizing a Samsung Neo series QLED as a WiiM player.
