### ISSUE TITLE
[Bug]: Spotify cover art not working

### ISSUE THREAD

**Issue by colings** [mjcumming/wiim#158]
### Pre-submission Checklist

- [x] I have searched existing issues and this is not a duplicate
- [x] I am using the latest version of the WiiM integration
- [x] I have enabled debug logging and included relevant logs below
- [x] I have included the integration diagnostics

### Integration Version

1.0.48

### Home Assistant Version

2025.12.3

### Primary WiiM Device Model

WiiM Amp

### Primary Device Name

Klipsch

### Is this device part of a group?

No - device is standalone

### Grouped Devices Details

The cover art hasn't been working for Spotify for at least a few versions. I was on 1.0.46 and it wasn't working, and when I updated to latest it still wasn't.

### Bug Description

Play a track on Spotify, the album art will be the Wiim logo.

### Steps to Reproduce

Same as description

### Configuration

```yaml

```

### Integration Diagnostics

{
  "home_assistant": {
    "installation_type": "Home Assistant OS",
    "version": "2025.12.3",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.13.9",
    "docker": true,
    "arch": "x86_64",
    "timezone": "America/Chicago",
    "os_name": "Linux",
    "os_version": "6.12.51-haos",
    "container_arch": "amd64",
    "supervisor": "2025.12.3",
    "host_os": "Home Assistant OS 16.3",
    "docker_version": "28.3.3",
    "chassis": "embedded",
    "run_as_root": true
  },
  "custom_components": {
    "fordpass": {
      "documentation": "https://github.com/itchannel/fordpass-ha",
      "version": "0.1.80",
      "requirements": []
    },
    "alexa_media": {
      "documentation": "https://github.com/alandtse/alexa_media_player/wiki",
      "version": "5.8.2",
      "requirements": [
        "alexapy==1.29.12",
        "packaging>=20.3",
        "wrapt>=1.14.0"
      ]
    },
    "wiim": {
      "documentation": "https://github.com/mjcumming/wiim",
      "version": "1.0.48",
      "requirements": [
        "pywiim==2.1.57"
      ]
    },
    "solaredge_modbus": {
      "documentation": "https://github.com/binsentsu/home-assistant-solaredge-modbus",
      "version": "2.2.1",
      "requirements": [
        "pymodbus==3.11.2"
      ]
    },
    "roomba_rest980": {
      "documentation": "https://github.com/ia74/roomba_rest980",
      "version": "1.13.0",
      "requirements": [
        "aiofiles==24.1.0"
      ]
    },
    "webrtc": {
      "documentation": "https://github.com/AlexxIT/WebRTC",
      "version": "v3.6.1",
      "requirements": []
    },
    "places": {
      "documentation": "https://github.com/custom-components/places",
      "version": "v2.9.2",
      "requirements": [
        "cachetools"
      ]
    },
    "alarmo": {
      "documentation": "https://github.com/nielsfaber/alarmo",
      "version": "1.10.13",
      "requirements": []
    },
    "gmg": {
      "documentation": "https://github.com/KyleLeMarbe/gmg_home_assistant",
      "version": "1.0.6",
      "requirements": []
    },
    "pirateweather": {
      "documentation": "https://github.com/alexander0042/pirate-weather-ha",
      "version": "1.8.2",
      "requirements": []
    },
    "bubble_card_tools": {
      "documentation": "https://github.com/Clooos/Bubble-Card-Tools",
      "version": "1.0.0",
      "requirements": []
    },
    "browser_mod": {
      "documentation": "https://github.com/thomasloven/hass-browser_mod/blob/master/README.md",
      "version": "2.6.4",
      "requirements": []
    },
    "ha_carrier": {
      "documentation": "https://github.com/dahlb/ha_carrier",
      "version": "2.16.0",
      "requirements": [
        "carrier-api==2.11.0"
      ]
    },
    "battery_notes": {
      "documentation": "https://andrew-codechimp.github.io/HA-Battery-Notes/",
      "version": "3.1.0",
      "requirements": []
    },
    "bambu_lab": {
      "documentation": "https://github.com/greghesp/ha-bambulab",
      "version": "2.2.18",
      "requirements": [
        "beautifulsoup4"
      ]
    },
    "synology_virtual_album": {
      "documentation": "https://github.com/colings/synology_virtual_album",
      "version": "0.9.0",
      "requirements": [
        "py-synologydsm-api"
      ]
    },
    "hacs": {
      "documentation": "https://hacs.xyz/docs/use/",
      "version": "2.0.5",
      "requirements": [
        "aiogithubapi>=22.10.1"
      ]
    },
    "spotifyplus": {
      "documentation": "https://github.com/thlucas1/homeassistantcomponent_spotifyplus/wiki/Device-Configuration-Options#integration-options",
      "version": "v1.0.187",
      "requirements": [
        "numpy>=2.3.2",
        "oauthlib>=3.2.2",
        "pillow>=11.3.0",
        "platformdirs>=4.1.0",
        "requests>=2.31.0",
        "requests_oauthlib>=1.3.1",
        "smartinspectpython>=3.0.38",
        "spotifywebapipython>=1.0.256",
        "urllib3>=2.0",
        "zeroconf>=0.132.2"
      ]
    },
    "frigate": {
      "documentation": "https://github.com/blakeblackshear/frigate",
      "version": "5.13.0",
      "requirements": [
        "hass-web-proxy-lib==0.0.7"
      ]
    }
  },
  "integration_manifest": {
    "domain": "wiim",
    "name": "WiiM",
    "codeowners": [
      "mjcumming"
    ],
    "config_flow": true,
    "dependencies": [
      "http"
    ],
    "documentation": "https://github.com/mjcumming/wiim",
    "integration_type": "device",
    "iot_class": "local_polling",
    "issue_tracker": "https://github.com/mjcumming/wiim/issues",
    "quality_scale": "silver",
    "requirements": [
      "pywiim==2.1.57"
    ],
    "ssdp": [
      {
        "deviceType": "urn:schemas-upnp-org:device:MediaRenderer:1",
        "st": "urn:schemas-upnp-org:device:MediaRenderer:1"
      }
    ],
    "version": "1.0.48",
    "zeroconf": [
      {
        "type": "_linkplay._tcp.local."
      }
    ],
    "is_built_in": false,
    "overwrites_built_in": false
  },
  "setup_times": {
    "null": {
      "setup": 0.0001005600206553936
    },
    "01KC4PFS3JVV6NNY7MFV627ERH": {
      "wait_import_platforms": -1.3868258288130164,
      "config_entry_setup": 3.725808247923851
    }
  },
  "data": {
    "pywiim_version": "2.1.57",
    "integration_overview": {
      "total_devices": 1,
      "available_devices": 1,
      "roles": {
        "solo": 1,
        "master": 0,
        "slave": 0
      },
      "models": [
        "WiiM_AMP"
      ]
    },
    "this_device": {
      "name": "Klipsch",
      "model": "WiiM_AMP",
      "firmware": "Linkplay.5.0.735950",
      "role": "solo",
      "available": true
    },
    "coordinator": {
      "update_interval_seconds": 1.0,
      "last_update_success": true
    },
    "entry_data": {
      "capabilities": {
        "audio_pro_generation": "original",
        "device_type": "WiiM_AMP",
        "firmware_version": "Linkplay.5.0.735950",
        "is_legacy_device": false,
        "is_wiim_device": true,
        "led_command_format": "standard",
        "max_alarm_slots": 3,
        "presets_full_data": true,
        "protocol_priority": [
          "https",
          "http"
        ],
        "response_timeout": 2.0,
        "retry_count": 2,
        "status_endpoint": "/httpapi.asp?command=getPlayerStatusEx",
        "supports_alarms": true,
        "supports_audio_output": true,
        "supports_enhanced_grouping": true,
        "supports_eq": true,
        "supports_firmware_install": true,
        "supports_getslavelist": true,
        "supports_getstatuse": true,
        "supports_led_control": true,
        "supports_metadata": false,
        "supports_player_status_ex": true,
        "supports_presets": true,
        "supports_sleep_timer": true,
        "vendor": "wiim"
      },
      "endpoint": "https://192.168.1.19:443",
      "host": "**REDACTED**"
    },
    "entry_options": {}
  },
  "issues": []
}

### Debug Logs

```text
2025-12-19 10:21:32.798 WARNING (MainThread) [pywiim.upnp.health] 🔴 UPnP events appear DEGRADED: 100.0% miss rate (3/3 changes missed)
2025-12-19 10:21:32.798 WARNING (MainThread) [pywiim.upnp.health]    → Switching to fast polling (1 second) to compensate
2025-12-19 10:25:28.625 WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to listdir with args ('/config/deps/lib/python3.13/site-packages',) inside the event loop by custom integration 'wiim' at custom_components/wiim/system_health.py, line 50: pywiim_version = metadata.version("pywiim") (offender: /usr/local/lib/python3.13/site-packages/importlib_metadata/__init__.py, line 817: return os.listdir(self.root or '.')), please create a bug report at https://github.com/mjcumming/wiim/issues
For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#listdir
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 229, in <module>
    sys.exit(main())
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 215, in main
    exit_code = runner.run(runtime_conf)
  File "/usr/src/homeassistant/homeassistant/runner.py", line 289, in run
    return loop.run_until_complete(setup_and_run_hass(runtime_config))
  File "/usr/local/lib/python3.13/asyncio/base_events.py", line 712, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.13/asyncio/base_events.py", line 683, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.13/asyncio/base_events.py", line 2050, in _run_once
    handle._run()
  File "/usr/local/lib/python3.13/asyncio/events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/src/homeassistant/homeassistant/components/system_health/__init__.py", line 89, in get_integration_info
    data = await registration.info_callback(hass)
  File "/config/custom_components/wiim/system_health.py", line 50, in system_health_info
    pywiim_version = metadata.version("pywiim")

2025-12-19 10:25:28.648 WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to read_text with args (PosixPath('/usr/local/lib/python3.13/site-packages/pywiim-2.1.57.dist-info/METADATA'),) inside the event loop by custom integration 'wiim' at custom_components/wiim/system_health.py, line 50: pywiim_version = metadata.version("pywiim") (offender: /usr/local/lib/python3.13/site-packages/importlib_metadata/__init__.py, line 998: return self._path.joinpath(filename).read_text(encoding='utf-8')), please create a bug report at https://github.com/mjcumming/wiim/issues
For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#read_text
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 229, in <module>
    sys.exit(main())
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 215, in main
    exit_code = runner.run(runtime_conf)
  File "/usr/src/homeassistant/homeassistant/runner.py", line 289, in run
    return loop.run_until_complete(setup_and_run_hass(runtime_config))
  File "/usr/local/lib/python3.13/asyncio/base_events.py", line 712, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.13/asyncio/base_events.py", line 683, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.13/asyncio/base_events.py", line 2050, in _run_once
    handle._run()
  File "/usr/local/lib/python3.13/asyncio/events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/src/homeassistant/homeassistant/components/system_health/__init__.py", line 89, in get_integration_info
    data = await registration.info_callback(hass)
  File "/config/custom_components/wiim/system_health.py", line 50, in system_health_info
    pywiim_version = metadata.version("pywiim")

2025-12-19 10:25:28.659 WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to open with args (PosixPath('/usr/local/lib/python3.13/site-packages/pywiim-2.1.57.dist-info/METADATA'),) inside the event loop by custom integration 'wiim' at custom_components/wiim/system_health.py, line 50: pywiim_version = metadata.version("pywiim") (offender: /usr/local/lib/python3.13/pathlib/_abc.py, line 632: with self.open(mode='r', encoding=encoding, errors=errors, newline=newline) as f:), please create a bug report at https://github.com/mjcumming/wiim/issues
For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#open
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 229, in <module>
    sys.exit(main())
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 215, in main
    exit_code = runner.run(runtime_conf)
  File "/usr/src/homeassistant/homeassistant/runner.py", line 289, in run
    return loop.run_until_complete(setup_and_run_hass(runtime_config))
  File "/usr/local/lib/python3.13/asyncio/base_events.py", line 712, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.13/asyncio/base_events.py", line 683, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.13/asyncio/base_events.py", line 2050, in _run_once
    handle._run()
  File "/usr/local/lib/python3.13/asyncio/events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/src/homeassistant/homeassistant/components/system_health/__init__.py", line 89, in get_integration_info
    data = await registration.info_callback(hass)
  File "/config/custom_components/wiim/system_health.py", line 50, in system_health_info
    pywiim_version = metadata.version("pywiim")

2025-12-19 10:26:07.950 DEBUG (MainThread) [custom_components.wiim.config_flow] Zeroconf discovery for host: 192.168.1.21
2025-12-19 10:26:07.977 DEBUG (MainThread) [custom_components.wiim.config_flow] Zeroconf discovery for host: 192.168.1.19
2025-12-19 10:26:08.140 DEBUG (MainThread) [custom_components.wiim.media_player_base] [Klipsch] Coordinator update (state=playing, raw_pos=63, raw_dur=162)
2025-12-19 10:26:08.141 DEBUG (MainThread) [custom_components.wiim.media_player_base] [Klipsch] Published position=63 (ts=2025-12-19 16:26:08.141206+00:00) duration=162
2025-12-19 10:26:08.144 DEBUG (MainThread) [custom_components.wiim.coordinator] Poll result for 192.168.1.19: state=play, pos=63, dur=162, title='Paper Low'
2025-12-19 10:26:08.145 DEBUG (MainThread) [custom_components.wiim.media_player_base] [Klipsch] Coordinator update (state=playing, raw_pos=63, raw_dur=162)
2025-12-19 10:26:08.145 DEBUG (MainThread) [custom_components.wiim.media_player_base] [Klipsch] Published position=63 (ts=2025-12-19 16:26:08.145185+00:00) duration=162
2025-12-19 10:26:08.147 DEBUG (MainThread) [custom_components.wiim.coordinator] Finished fetching WiiM 192.168.1.19 data in 0.451 seconds (success: True)
2025-12-19 10:26:08.149 DEBUG (MainThread) [custom_components.wiim.media_player_base] [Klipsch] Coordinator update (state=playing, raw_pos=63, raw_dur=162)
2025-12-19 10:26:08.149 DEBUG (MainThread) [custom_components.wiim.media_player_base] [Klipsch] Published position=63 (ts=2025-12-19 16:26:08.149361+00:00) duration=162
2025-12-19 10:26:09.137 DEBUG (MainThread) [custom_components.wiim.media_player_base] [Klipsch] Coordinator update (state=playing, raw_pos=64, raw_dur=162)
2025-12-19 10:26:09.137 DEBUG (MainThread) [custom_components.wiim.media_player_base] [Klipsch] Published position=64 (ts=2025-12-19 16:26:09.137835+00:00) duration=162
2025-12-19 10:26:09.141 DEBUG (MainThread) [custom_components.wiim.coordinator] Poll result for 192.168.1.19: state=play, pos=64, dur=162, title='Paper Low'
2025-12-19 10:26:09.141 DEBUG (MainThread) [custom_components.wiim.media_player_base] [Klipsch] Coordinator update (state=playing, raw_pos=64, raw_dur=162)
2025-12-19 10:26:09.141 DEBUG (MainThread) [custom_components.wiim.media_player_base] [Klipsch] Published position=64 (ts=2025-12-19 16:26:09.141713+00:00) duration=162
2025-12-19 10:26:09.145 DEBUG (MainThread) [custom_components.wiim.coordinator] Finished fetching WiiM 192.168.1.19 data in 0.449 seconds (success: True)
2025-12-19 10:26:09.145 DEBUG (MainThread) [custom_components.wiim.media_player_base] [Klipsch] Coordinator update (state=playing, raw_pos=64, raw_dur=162)
2025-12-19 10:26:09.146 DEBUG (MainThread) [custom_components.wiim.media_player_base] [Klipsch] Published position=64 (ts=2025-12-19 16:26:09.146279+00:00) duration=162
2025-12-19 10:26:10.130 DEBUG (MainThread) [custom_components.wiim.media_player_base] [Klipsch] Coordinator update (state=playing, raw_pos=65, raw_dur=162)
2025-12-19 10:26:10.131 DEBUG (MainThread) [custom_components.wiim.media_player_base] [Klipsch] Published position=65 (ts=2025-12-19 16:26:10.130968+00:00) duration=162
2025-12-19 10:26:10.135 DEBUG (MainThread) [custom_components.wiim.coordinator] Poll result for 192.168.1.19: state=play, pos=65, dur=162, title='Paper Low'
2025-12-19 10:26:10.135 DEBUG (MainThread) [custom_components.wiim.media_player_base] [Klipsch] Coordinator update (state=playing, raw_pos=65, raw_dur=162)
2025-12-19 10:26:10.135 DEBUG (MainThread) [custom_components.wiim.media_player_base] [Klipsch] Published position=65 (ts=2025-12-19 16:26:10.135596+00:00) duration=162
2025-12-19 10:26:10.141 DEBUG (MainThread) [custom_components.wiim.coordinator] Finished fetching WiiM 192.168.1.19 data in 0.444 seconds (success: True)
2025-12-19 10:26:10.141 DEBUG (MainThread) [custom_components.wiim.media_player_base] [Klipsch] Coordinator update (state=playing, raw_pos=65, raw_dur=162)
2025-12-19 10:26:10.141 DEBUG (MainThread) [custom_components.wiim.media_player_base] [Klipsch] Published position=65 (ts=2025-12-19 16:26:10.141713+00:00) duration=162
2025-12-19 10:26:11.176 DEBUG (MainThread) [custom_components.wiim.media_player_base] [Klipsch] Coordinator update (state=playing, raw_pos=66, raw_dur=162)
2025-12-19 10:26:11.176 DEBUG (MainThread) [custom_components.wiim.media_player_base] [Klipsch] Published position=66 (ts=2025-12-19 16:26:11.176405+00:00) duration=162
2025-12-19 10:26:11.179 DEBUG (MainThread) [custom_components.wiim.coordinator] Poll result for 192.168.1.19: state=play, pos=66, dur=162, title='Paper Low'
2025-12-19 10:26:11.179 DEBUG (MainThread) [custom_components.wiim.media_player_base] [Klipsch] Coordinator update (state=playing, raw_pos=66, raw_dur=162)
2025-12-19 10:26:11.179 DEBUG (MainThread) [custom_components.wiim.media_player_base] [Klipsch] Published position=66 (ts=2025-12-19 16:26:11.179477+00:00) duration=162
2025-12-19 10:26:11.181 DEBUG (MainThread) [custom_components.wiim.coordinator] Finished fetching WiiM 192.168.1.19 data in 0.485 seconds (success: True)
2025-12-19 10:26:11.181 DEBUG (MainThread) [custom_components.wiim.media_player_base] [Klipsch] Coordinator update (state=playing, raw_pos=66, raw_dur=162)
2025-12-19 10:26:11.181 DEBUG (MainThread) [custom_components.wiim.media_player_base] [Klipsch] Published position=66 (ts=2025-12-19 16:26:11.181416+00:00) duration=162
2025-12-19 10:26:12.134 DEBUG (MainThread) [custom_components.wiim.media_player_base] [Klipsch] Coordinator update (state=playing, raw_pos=67, raw_dur=162)
2025-12-19 10:26:12.134 DEBUG (MainThread) [custom_components.wiim.media_player_base] [Klipsch] Published position=67 (ts=2025-12-19 16:26:12.134839+00:00) duration=162
2025-12-19 10:26:12.138 DEBUG (MainThread) [custom_components.wiim.coordinator] Poll result for 192.168.1.19: state=play, pos=67, dur=162, title='Paper Low'
2025-12-19 10:26:12.138 DEBUG (MainThread) [custom_components.wiim.media_player_base] [Klipsch] Coordinator update (state=playing, raw_pos=67, raw_dur=162)
2025-12-19 10:26:12.138 DEBUG (MainThread) [custom_components.wiim.media_player_base] [Klipsch] Published position=67 (ts=2025-12-19 16:26:12.138431+00:00) duration=162
2025-12-19 10:26:12.144 DEBUG (MainThread) [custom_components.wiim.coordinator] Finished fetching WiiM 192.168.1.19 data in 0.447 seconds (success: True)
2025-12-19 10:26:12.145 DEBUG (MainThread) [custom_components.wiim.media_player_base] [Klipsch] Coordinator update (state=playing, raw_pos=67, raw_dur=162)
2025-12-19 10:26:12.145 DEBUG (MainThread) [custom_components.wiim.media_player_base] [Klipsch] Published position=67 (ts=2025-12-19 16:26:12.145646+00:00) duration=162
2025-12-19 10:26:13.131 DEBUG (MainThread) [custom_components.wiim.media_player_base] [Klipsch] Coordinator update (state=playing, raw_pos=68, raw_dur=162)
2025-12-19 10:26:13.131 DEBUG (MainThread) [custom_components.wiim.media_player_base] [Klipsch] Published position=68 (ts=2025-12-19 16:26:13.131782+00:00) duration=162
2025-12-19 10:26:13.135 DEBUG (MainThread) [custom_components.wiim.coordinator] Poll result for 192.168.1.19: state=play, pos=68, dur=162, title='Paper Low'
2025-12-19 10:26:13.135 DEBUG (MainThread) [custom_components.wiim.media_player_base] [Klipsch] Coordinator update (state=playing, raw_pos=68, raw_dur=162)
2025-12-19 10:26:13.135 DEBUG (MainThread) [custom_components.wiim.media_player_base] [Klipsch] Published position=68 (ts=2025-12-19 16:26:13.135890+00:00) duration=162
2025-12-19 10:26:13.140 DEBUG (MainThread) [custom_components.wiim.coordinator] Finished fetching WiiM 192.168.1.19 data in 0.444 seconds (success: True)
2025-12-19 10:26:13.140 DEBUG (MainThread) [custom_components.wiim.media_player_base] [Klipsch] Coordinator update (state=playing, raw_pos=68, raw_dur=162)
2025-12-19 10:26:13.141 DEBUG (MainThread) [custom_components.wiim.media_player_base] [Klipsch] Published position=68 (ts=2025-12-19 16:26:13.140963+00:00) duration=162
2025-12-19 10:26:14.135 DEBUG (MainThread) [custom_components.wiim.media_player_base] [Klipsch] Coordinator update (state=playing, raw_pos=0, raw_dur=213)
2025-12-19 10:26:14.135 DEBUG (MainThread) [custom_components.wiim.media_player_base] [Klipsch] Published position=0 (ts=2025-12-19 16:26:14.135539+00:00) duration=213
2025-12-19 10:26:14.138 DEBUG (MainThread) [custom_components.wiim.coordinator] Poll result for 192.168.1.19: state=play, pos=0, dur=213, title='EL MUNDO SE VA A ACABAR'
2025-12-19 10:26:14.138 DEBUG (MainThread) [custom_components.wiim.media_player_base] [Klipsch] Coordinator update (state=playing, raw_pos=0, raw_dur=213)
2025-12-19 10:26:14.139 DEBUG (MainThread) [custom_components.wiim.media_player_base] [Klipsch] Published position=0 (ts=2025-12-19 16:26:14.139024+00:00) duration=213
2025-12-19 10:26:14.144 DEBUG (MainThread) [custom_components.wiim.coordinator] Finished fetching WiiM 192.168.1.19 data in 0.448 seconds (success: True)
2025-12-19 10:26:14.145 DEBUG (MainThread) [custom_components.wiim.media_player_base] [Klipsch] Coordinator update (state=playing, raw_pos=0, raw_dur=213)
2025-12-19 10:26:14.145 DEBUG (MainThread) [custom_components.wiim.media_player_base] [Klipsch] Published position=0 (ts=2025-12-19 16:26:14.145331+00:00) duration=213
2025-12-19 10:26:15.149 DEBUG (MainThread) [custom_components.wiim.media_player_base] [Klipsch] Coordinator update (state=playing, raw_pos=1, raw_dur=213)
2025-12-19 10:26:15.149 DEBUG (MainThread) [custom_components.wiim.media_player_base] [Klipsch] Published position=1 (ts=2025-12-19 16:26:15.149762+00:00) duration=213
2025-12-19 10:26:15.151 DEBUG (MainThread) [custom_components.wiim.coordinator] Poll result for 192.168.1.19: state=play, pos=1, dur=213, title='EL MUNDO SE VA A ACABAR'
2025-12-19 10:26:15.152 DEBUG (MainThread) [custom_components.wiim.media_player_base] [Klipsch] Coordinator update (state=playing, raw_pos=1, raw_dur=213)
2025-12-19 10:26:15.152 DEBUG (MainThread) [custom_components.wiim.media_player_base] [Klipsch] Published position=1 (ts=2025-12-19 16:26:15.152107+00:00) duration=213
2025-12-19 10:26:15.153 DEBUG (MainThread) [custom_components.wiim.coordinator] Finished fetching WiiM 192.168.1.19 data in 0.457 seconds (success: True)
2025-12-19 10:26:15.153 DEBUG (MainThread) [custom_components.wiim.media_player_base] [Klipsch] Coordinator update (state=playing, raw_pos=1, raw_dur=213)
2025-12-19 10:26:15.153 DEBUG (MainThread) [custom_components.wiim.media_player_base] [Klipsch] Published position=1 (ts=2025-12-19 16:26:15.153512+00:00) duration=213
2025-12-19 10:26:16.170 DEBUG (MainThread) [custom_components.wiim.media_player_base] [Klipsch] Coordinator update (state=playing, raw_pos=2, raw_dur=213)
2025-12-19 10:26:16.170 DEBUG (MainThread) [custom_components.wiim.media_player_base] [Klipsch] Published position=2 (ts=2025-12-19 16:26:16.170813+00:00) duration=213
2025-12-19 10:26:16.173 DEBUG (MainThread) [custom_components.wiim.coordinator] Poll result for 192.168.1.19: state=play, pos=2, dur=213, title='EL MUNDO SE VA A ACABAR'
2025-12-19 10:26:16.173 DEBUG (MainThread) [custom_components.wiim.media_player_base] [Klipsch] Coordinator update (state=playing, raw_pos=2, raw_dur=213)
2025-12-19 10:26:16.173 DEBUG (MainThread) [custom_components.wiim.media_player_base] [Klipsch] Published position=2 (ts=2025-12-19 16:26:16.173396+00:00) duration=213
2025-12-19 10:26:16.174 DEBUG (MainThread) [custom_components.wiim.coordinator] Finished fetching WiiM 192.168.1.19 data in 0.478 seconds (success: True)
2025-12-19 10:26:16.174 DEBUG (MainThread) [custom_components.wiim.media_player_base] [Klipsch] Coordinator update (state=playing, raw_pos=2, raw_dur=213)
2025-12-19 10:26:16.174 DEBUG (MainThread) [custom_components.wiim.media_player_base] [Klipsch] Published position=2 (ts=2025-12-19 16:26:16.174913+00:00) duration=213
2025-12-19 10:26:17.142 DEBUG (MainThread) [custom_components.wiim.media_player_base] [Klipsch] Coordinator update (state=playing, raw_pos=3, raw_dur=213)
2025-12-19 10:26:17.143 DEBUG (MainThread) [custom_components.wiim.media_player_base] [Klipsch] Published position=3 (ts=2025-12-19 16:26:17.143157+00:00) duration=213
2025-12-19 10:26:17.145 DEBUG (MainThread) [custom_components.wiim.coordinator] Poll result for 192.168.1.19: state=play, pos=3, dur=213, title='EL MUNDO SE VA A ACABAR'
2025-12-19 10:26:17.146 DEBUG (MainThread) [custom_components.wiim.media_player_base] [Klipsch] Coordinator update (state=playing, raw_pos=3, raw_dur=213)
2025-12-19 10:26:17.146 DEBUG (MainThread) [custom_components.wiim.media_player_base] [Klipsch] Published position=3 (ts=2025-12-19 16:26:17.146202+00:00) duration=213
2025-12-19 10:26:17.147 DEBUG (MainThread) [custom_components.wiim.coordinator] Finished fetching WiiM 192.168.1.19 data in 0.451 seconds (success: True)
2025-12-19 10:26:17.148 DEBUG (MainThread) [custom_components.wiim.media_player_base] [Klipsch] Coordinator update (state=playing, raw_pos=3, raw_dur=213)
2025-12-19 10:26:17.148 DEBUG (MainThread) [custom_components.wiim.media_player_base] [Klipsch] Published position=3 (ts=2025-12-19 16:26:17.148116+00:00) duration=213
2025-12-19 10:26:18.145 DEBUG (MainThread) [custom_components.wiim.media_player_base] [Klipsch] Coordinator update (state=playing, raw_pos=4, raw_dur=213)
2025-12-19 10:26:18.145 DEBUG (MainThread) [custom_components.wiim.media_player_base] [Klipsch] Published position=4 (ts=2025-12-19 16:26:18.145392+00:00) duration=213
2025-12-19 10:26:18.148 DEBUG (MainThread) [custom_components.wiim.coordinator] Poll result for 192.168.1.19: state=play, pos=4, dur=213, title='EL MUNDO SE VA A ACABAR'
2025-12-19 10:26:18.148 DEBUG (MainThread) [custom_components.wiim.media_player_base] [Klipsch] Coordinator update (state=playing, raw_pos=4, raw_dur=213)
2025-12-19 10:26:18.148 DEBUG (MainThread) [custom_components.wiim.media_player_base] [Klipsch] Published position=4 (ts=2025-12-19 16:26:18.148835+00:00) duration=213
2025-12-19 10:26:18.152 DEBUG (MainThread) [custom_components.wiim.coordinator] Finished fetching WiiM 192.168.1.19 data in 0.456 seconds (success: True)
2025-12-19 10:26:18.153 DEBUG (MainThread) [custom_components.wiim.media_player_base] [Klipsch] Coordinator update (state=playing, raw_pos=4, raw_dur=213)
2025-12-19 10:26:18.153 DEBUG (MainThread) [custom_components.wiim.media_player_base] [Klipsch] Published position=4 (ts=2025-12-19 16:26:18.153307+00:00) duration=213
```

### Installation Method

HACS

**Comment by mjcumming** [comment]
Should be fixed in .50 release - let me know!

**Comment by colings** [comment]
I updated to .50 and unfortunately I'm still not getting the album art. I can get new logs for you if that helps. I also noticed that the various sample rate, bit depth, etc sensors aren't working (they all just say unknown). That has also been happening for a few versions, I just forgot to mention it.

**Comment by SirJohnDoe** [comment]
> I updated to .50 and unfortunately I'm still not getting the album art. I can get new logs for you if that helps. I also noticed that the various sample rate, bit depth, etc sensors aren't working (they all just say unknown). That has also been happening for a few versions, I just forgot to mention it.

I had the same problem. After reinstalling the integration the album art started working again. Suddenly other sensors also started working (bitrate etc).

**Comment by colings** [comment]
Hey, you're right! At first I thought you just meant removing the entry and readding it, which didn't fix it. I completely deleted the integration in HACS, rebooted, redownloaded it, rebooted again, then everything was working.
