### ISSUE TITLE
[Feature]: Outputs / Bluetooth Pairing

### ISSUE THREAD

**Issue by Select446** [mjcumming/wiim#79]
### Pre-submission Checklist

- [x] I have searched existing issues and this feature hasn't been requested
- [x] This feature would be useful for other users, not just my specific setup
- [x] This feature aligns with Home Assistant's design principles

### Feature Category

Device Control (playback, volume, etc.)

### Problem Description

I often stream my line ins on Wiim pro to a separate bluetooth speaker outside. The Linkplay integration has outputs but doesnt appear to have bluetooth or pairing and i have ended up disabling it

### Proposed Solution

I would like to be able to select the outputs including Bluetooth from this integration (and therefore automate the process) without having to load up the Wiim App on my phone each time

### Alternative Solutions

Im not sure

### Priority Level

Low - Nice to have

### Use Case Details

I use the Wiim in two ways, streaming to it from Chromecast or Airplay, outputting to a mixer which is connected to booth speakers, or secondly streaming bluetooth from the Wiim to a portable speaker , with the inputs instead being the line outs of my mixer. When i change my input to mixer i could then initiate bluetooth pairing to my outdoor speaker 

### Contribution

- [ ] I would be willing to submit a pull request for this feature
- [x] I would be willing to test this feature once implemented
- [ ] I would be willing to help with documentation for this feature

**Comment by mjcumming** [comment]
Try the .31 release - this uses the WiiM API to turn on the bluetooth - it  should work for an already paired device.

**Comment by Select446** [comment]
Thanks for looking at this 👍 I've just tried 0.31 and can see the new Audio Output section and a sensor entry for bluetooth but all entities show unavailable (i've also deleted the integration which immediately auto detects the Wiim buts goes straight back to unavailable) There is a lot of log activity for select.wiim_pro_audio_output_mode Bluetooth Out (checking every 15 seconds) but remains unavailable. Log also states:

Error fetching WiiM 172.16.0.72 data: Error updating WiiM device: Request to https://172.16.0.72:443/httpapi.asp?command=getPlayerStatusEx failed:

and

Logger: custom_components.wiim.api_base
Source: custom_components/wiim/api_base.py:265
integration: WiiM (documentation, issues)
First occurred: 23:35:26 (8 occurrences)
Last logged: 23:35:28

Connection lost to 172.16.0.82, will retry with protocol probe
Connection lost to 172.16.1.1, will retry with protocol probe
Connection lost to 172.16.0.24, will retry with protocol probe
Connection lost to 172.16.0.42, will retry with protocol probe

Although im not sure if these are new errors as didn't check the log prior to updating the integration

**Comment by mjcumming** [comment]
try .32 - should fix this - if not, include the expanded logging.

**Comment by Select446** [comment]
I cant get the integration to load at all now, and my home assistant never gets past wrapping up stage. I have two separate raspberry pi 4s, each with a copy of home assistant (one 32, one 64) so i tried the installing on the other too but both get stuck before fully loading after HA restart- rolling back to .31 returns them to normal state - i got this error in both logs:


This error originated from a custom integration.

Logger: homeassistant
Source: custom_components/wiim/api_base.py:282
integration: WiiM (documentation, issues)
First occurred: 15:31:14 (10 occurrences)
Last logged: 15:39:05

Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/config/custom_components/wiim/api_base.py", line 221, in _request_with_protocol_fallback
    p = urlsplit(self._endpoint)
  File "/usr/local/lib/python3.13/urllib/parse.py", line 514, in urlsplit
    raise ValueError("Invalid IPv6 URL")
ValueError: Invalid IPv6 URL

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/discovery_flow.py", line 137, in _async_start
    await gather_with_limited_concurrency(FLOW_INIT_LIMIT, *init_coros)
  File "/usr/src/homeassistant/homeassistant/util/async_.py", line 113, in gather_with_limited_concurrency
    return await gather(
           ^^^^^^^^^^^^^
    ...<2 lines>...
    )
    ^
  File "/usr/src/homeassistant/homeassistant/util/async_.py", line 111, in sem_task
    return await task
           ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1464, in async_init
    flow, result = await self._async_init(flow_id, handler, context, data)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1510, in _async_init
    result = await self._async_handle_step(flow, flow.init_step, data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 497, in _async_handle_step
    result: _FlowResultT = await getattr(flow, method)(user_input)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/wiim/config_flow.py", line 340, in async_step_zeroconf
    is_valid, device_name, device_uuid = await validate_wiim_device(host)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/wiim/config_flow.py", line 73, in validate_wiim_device
    status = await client.get_status()
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/wiim/api_base.py", line 439, in get_status
    raw = await self._request(API_ENDPOINT_STATUS)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/wiim/api_base.py", line 182, in _request
    result = await self._request_with_protocol_fallback(endpoint, method, **kwargs)


Also the integration didnt auto-detect which im guessing is due to HA being stuck in wrapping up stage but worth a mention - trying to add the integration resulted in "unknown error" in config flow

**Comment by mjcumming** [comment]
fix coming - introduced this bug fixing some discovery issues in another issue ...

**Comment by Select446** [comment]
Brill, thanks for your work 👍

Some more notes from testing now is i redownloaded .31, set it up then upgraded to .32 instead (rather than deleting the integration this time) and restarted - although i still get the same log error as above, the integration does load and populates all entities as expected. It can see that im connected to Bluetooh and will change inputs from Bluetooth however switching back from the integration does not re connect.

![image](https://github.com/user-attachments/assets/0dba6a56-d8c0-44e5-bbfd-47c9679965b3)

![image](https://github.com/user-attachments/assets/0688ec49-a804-481c-9989-e417c2389805)

There doesn't appear to be any error log info (i've also enabled debug logging) when i switch the output to bluetooth however the title of the drop down "Audio Output Mode" flashes a number of times as if it is changing state rapidly

**Comment by mjcumming** [comment]
I think/hope .34 fixes this...

**Comment by Select446** [comment]
I've upgraded to the latest version and suddenly lots of new devices appeared:
![image](https://github.com/user-attachments/assets/1bc94ef1-f95c-47a4-984e-0e9484bb1d80)

Looking at the ip addresses they appear to be my Bose Hoome Speaker, Denon Amp and some of my Sonos Speakers

If i try to add any of them it just fails but thought it was worth a try when testing

For the bluetooth, it still appears as before (integration knows when bluetooth connected, can disconnect, but cant reconnect) 

comparing between the Wiim app and integration during selecting outputs (in the integration), for each of coax, line and optical outs, the mobile app and device updates and highlights the selected output as expected , for bluetooth no selection is shown in the app (rather than staying on the previously selected input - so it definitely registers a new selection)

**Comment by mjcumming** [comment]
When adding better discovery for the Audio pro devices - this bug got introduced.. should be fixed in .38

**Comment by Select446** [comment]
No problem 👍

Just tried 0.38 but got an extra 3 new devices discovered: 

![image](https://github.com/user-attachments/assets/276231f5-e8ef-4749-a1cf-938ae29054ed)

**Comment by mjcumming** [comment]
ok, how about .40 - fixed?

**Comment by Select446** [comment]
I've tried .40 and .42 but in both cases the audio output is greyed out

![image](https://github.com/user-attachments/assets/f4cb0d5c-e96e-4c1d-95dd-7f4ad2255554)

Discovered devices remain as before

In both cases i upgraded rather than full deletion

**Comment by mjcumming** [comment]
ok, try .44, if no luck attached the logs and device diagnostics here.

**Comment by Select446** [comment]
Tested .44 with logs attached:

[home-assistant_wiim_2025-10-27T15-51-06.245Z.log](https://github.com/user-attachments/files/23168227/home-assistant_wiim_2025-10-27T15-51-06.245Z.log)


Also:

{
  "home_assistant": {
    "installation_type": "Home Assistant Container",
    "version": "2025.10.4",
    "dev": false,
    "hassio": false,
    "virtualenv": false,
    "python_version": "3.13.7",
    "docker": true,
    "arch": "aarch64",
    "timezone": "Europe/London",
    "os_name": "Linux",
    "os_version": "6.1.21-v8+",
    "container_arch": "armv7",
    "run_as_root": true
  },
  "custom_components": {
    "monitor_docker": {
      "documentation": "https://github.com/ualex73/monitor_docker",
      "version": "1.18",
      "requirements": [
        "aiodocker==0.22.0",
        "python-dateutil==2.9.0"
      ]
    },
    "teamtracker": {
      "documentation": "https://github.com/vasqued2/ha-teamtracker",
      "version": "0.1",
      "requirements": [
        "arrow",
        "aiofiles"
      ]
    },
    "advanced_snapshot": {
      "documentation": "https://github.com/Phil7989/advanced_snapshot",
      "version": "2025.2.3.1",
      "requirements": [
        "Pillow",
        "ffmpeg-python"
      ]
    },
    "xiaomi_home": {
      "documentation": "https://github.com/XiaoMi/ha_xiaomi_home/blob/main/README.md",
      "version": "v0.4.3",
      "requirements": [
        "construct>=2.10.56",
        "paho-mqtt",
        "numpy",
        "cryptography",
        "psutil"
      ]
    },
    "wiim": {
      "documentation": "https://github.com/mjcumming/wiim",
      "version": "0.1.44",
      "requirements": []
    },
    "spotcast": {
      "documentation": "https://github.com/fondberg/spotcast",
      "version": "v4.0.1",
      "requirements": [
        "spotipy==2.23.0"
      ]
    },
    "localtuya": {
      "documentation": "https://github.com/xZetsubou/hass-localtuya/",
      "version": "2025.10.0",
      "requirements": []
    },
    "plant": {
      "documentation": "https://github.com/Olen/homeassistant-plant/",
      "version": "2025.8.0",
      "requirements": [
        "async-timeout>=4.0.2"
      ]
    },
    "dreo": {
      "documentation": "https://github.com/jeffsteinbok/hass-dreo/blob/master/README.md",
      "version": "1.4.1",
      "requirements": [
        "websockets"
      ]
    },
    "bose": {
      "documentation": "https://github.com/cavefire/Bose-Homeassistant",
      "version": "1.0.2",
      "requirements": [
        "pybose==2025.8.1"
      ]
    },
    "remote_homeassistant": {
      "documentation": "https://github.com/custom-components/remote_homeassistant",
      "version": "4.5",
      "requirements": []
    },
    "mycloud": {
      "documentation": "https://github.com/J-shw/wdnas_hacs",
      "version": "1.0.2",
      "requirements": [
        "wdnas-client>=0.8.3"
      ]
    },
    "watchman": {
      "documentation": "https://github.com/dummylabs/thewatchman",
      "version": "0.6.5",
      "requirements": [
        "prettytable==3.12.0"
      ]
    },
    "network_scanner": {
      "documentation": "https://github.com/parvez/network_scanner",
      "version": "1.0.7",
      "requirements": [
        "python-nmap"
      ]
    },
    "openai_stt": {
      "documentation": "https://github.com/einToast/openai_stt_ha",
      "version": "1.2.0",
      "requirements": []
    },
    "skyq": {
      "documentation": "https://github.com/RogerSelwyn/Home_Assistant_SkyQ_MediaPlayer",
      "version": "v2.13.1",
      "requirements": [
        "pyskyqremote==0.3.26"
      ]
    },
    "alexa_media": {
      "documentation": "https://github.com/alandtse/alexa_media_player/wiki",
      "version": "5.7.9",
      "requirements": [
        "alexapy==1.29.8",
        "packaging>=20.3",
        "wrapt>=1.14.0"
      ]
    },
    "hpprinter": {
      "documentation": "https://github.com/elad-bar/ha-hpprinter",
      "version": "2.0.5",
      "requirements": [
        "xmltodict~=0.13.0",
        "flatten_json",
        "defusedxml"
      ]
    },
    "hacs": {
      "documentation": "https://hacs.xyz/docs/use/",
      "version": "2.0.5",
      "requirements": [
        "aiogithubapi>=22.10.1"
      ]
    },
    "meross_lan": {
      "documentation": "https://github.com/krahabb/meross_lan",
      "version": "5.6.0",
      "requirements": []
    },
    "xiaomi_miot": {
      "documentation": "https://github.com/al-one/hass-xiaomi-miot",
      "version": "1.1.0",
      "requirements": [
        "construct>=2.10.68",
        "python-miio>=0.5.12",
        "micloud>=0.5"
      ]
    },
    "tplink_router": {
      "documentation": "https://github.com/AlexandrErohin/home-assistant-tplink-router",
      "version": "v2.12.2",
      "requirements": [
        "tplinkrouterc6u==5.10.2"
      ]
    },
    "attribute_as_sensor": {
      "documentation": "https://github.com/gjohansson-ST/attribute_as_sensor/blob/master/readme.md",
      "version": "1.6",
      "requirements": []
    },
    "media_player_template": {
      "documentation": "https://github.com/Sennevds/media_player.template",
      "version": "1.0.2",
      "requirements": []
    },
    "hon": {
      "documentation": "https://github.com/gvigroux/hon",
      "version": "0.7.16",
      "requirements": []
    },
    "dash_cast": {
      "documentation": "https://github.com/AlexxIT/DashCast",
      "version": "1.1.1",
      "requirements": []
    },
    "nest_protect": {
      "documentation": "https://github.com/imicknl/ha-nest-protect",
      "version": "0.4.1",
      "requirements": []
    },
    "config_editor": {
      "documentation": "https://github.com/junkfix/config-editor-card",
      "version": "5.0.0",
      "requirements": []
    },
    "waveshare_ups_hat": {
      "documentation": "https://github.com/mykhailog/hacs_waveshare_ups_hat",
      "version": "0.1.6",
      "requirements": [
        "smbus2>=0.4.2"
      ]
    },
    "pyscript": {
      "documentation": "https://github.com/custom-components/pyscript",
      "version": "1.6.4",
      "requirements": [
        "croniter==6.0.0",
        "watchdog==6.0.0"
      ]
    },
    "average": {
      "documentation": "https://github.com/Limych/ha-average",
      "version": "2.4.0",
      "requirements": [
        "pip>=21.3.1"
      ]
    },
    "ttlock": {
      "documentation": "https://github.com/jbergler/hass-ttlock",
      "version": "v0.7.2",
      "requirements": [
        "pydantic"
      ]
    }
  },
  "integration_manifest": {
    "domain": "wiim",
    "name": "WiiM",
    "codeowners": [
      "mjcumming"
    ],
    "config_flow": true,
    "dependencies": [],
    "documentation": "https://github.com/mjcumming/wiim",
    "integration_type": "device",
    "iot_class": "local_polling",
    "issue_tracker": "https://github.com/mjcumming/wiim/issues",
    "quality_scale": "silver",
    "requirements": [],
    "ssdp": [
      {
        "manufacturer": "WiiM",
        "st": "upnp:rootdevice"
      },
      {
        "manufacturer": "LinkPlay",
        "st": "upnp:rootdevice"
      },
      {
        "manufacturer": "WiiM",
        "device_type": "urn:schemas-upnp-org:device:MediaRenderer:1"
      },
      {
        "manufacturer": "LinkPlay",
        "device_type": "urn:schemas-upnp-org:device:MediaRenderer:1"
      },
      {
        "st": "urn:schemas-upnp-org:service:AVTransport:1"
      },
      {
        "st": "urn:schemas-upnp-org:service:RenderingControl:1"
      },
      {
        "st": "urn:schemas-upnp-org:service:ConnectionManager:1"
      }
    ],
    "version": "0.1.44",
    "zeroconf": [
      {
        "type": "_linkplay._tcp.local."
      }
    ],
    "is_built_in": false,
    "overwrites_built_in": false
  },
  "setup_times": {},
  "data": {
    "device_info": {
      "speaker_uuid": "FF98F09CF38DA23D12905F90",
      "name": "WiiM Pro",
      "model": "WiiM_Pro_with_gc4a",
      "firmware": "Linkplay.4.8.731953",
      "role": "solo",
      "available": true,
      "ip_address": {
        "ip": "**REDACTED**"
      },
      "mac_address": {
        "mac": "**REDACTED**"
      }
    },
    "group_info": {
      "role": "solo",
      "is_group_coordinator": false,
      "group_members_count": 0,
      "group_member_names": [],
      "coordinator_name": null
    },
    "media_info": {
      "playback_state": "playing",
      "volume_level": 1.0,
      "is_muted": false,
      "current_source": "Spotify",
      "media_title": "Acceptable in the 80's",
      "media_artist": "Calvin Harris",
      "media_album": "I Created Disco",
      "media_duration": 333,
      "media_position": 16,
      "media_image_url": "https://i.scdn.co/image/ab67616d0000b273d0b33add0e39952e5e721226",
      "shuffle_state": false,
      "repeat_mode": "one",
      "sound_mode": "Flat"
    },
    "api_capabilities": {
      "metadata_supported": true,
      "statusex_supported": null,
      "eq_supported": true,
      "presets_supported": false
    },
    "api_status": {
      "host": "**REDACTED**",
      "timeout": 2.0,
      "client_type": "<class 'custom_components.wiim.api.WiiMClient'>"
    },
    "model_data": {
      "status_model": {
        "play_state": "play",
        "volume": 100,
        "mute": false,
        "source": "spotify",
        "mode": "31",
        "position": 16,
        "duration": 333,
        "title": "Acceptable in the 80's",
        "artist": "Calvin Harris",
        "album": "I Created Disco",
        "entity_picture": "https://i.scdn.co/image/ab67616d0000b273d0b33add0e39952e5e721226",
        "cover_url": "https://i.scdn.co/image/ab67616d0000b273d0b33add0e39952e5e721226",
        "eq_preset": "flat",
        "loop_mode": 3,
        "play_mode": "repeat_one",
        "type": "0",
        "ch": "0",
        "vendor": "spotify:playlist:2DLPSGuAXEP3Vcsoovnru3",
        "position_ms": "16845",
        "offset_pts": "0",
        "duration_ms": "333680",
        "title_hex": "41636365707461626C6520696E207468652038302773",
        "artist_hex": "43616C76696E20486172726973",
        "album_hex": "49204372656174656420446973636F",
        "alarmflag": "0",
        "plicount": "0",
        "plicurr": "0",
        "power": true,
        "volume_level": 1.0,
        "position_updated_at": 370799.537498825,
        "audio_output": {
          "hardware": "4",
          "source": "0",
          "audiocast": "0"
        }
      },
      "device_model": {
        "uuid": "**REDACTED**",
        "name": "WiiM Pro",
        "model": "WiiM_Pro_with_gc4a",
        "firmware": "Linkplay.4.8.731953",
        "mac": "B8:13:32:E0:F9:32",
        "release_date": "20251009",
        "hardware": "AmlogicA113",
        "wmrm_version": "4.3",
        "mcu_ver": "0",
        "dsp_ver": "",
        "preset_key": 12,
        "group": "0",
        "version_update": "0",
        "latest_version": "0",
        "language": "en-GB",
        "ssid": "**REDACTED**",
        "hideSSID": "0",
        "build": "release",
        "priv_prj": "WiiM_Pro_with_gc4a",
        "project_build_name": "WiiM_Pro_with_gc4a",
        "FW_Release_version": "",
        "PCB_version": "1",
        "cast_enable": 1,
        "cast_usage_report": 1,
        "wmrm_sub_ver": "7",
        "expired": "0",
        "internet": "1",
        "BTMAC": "b8:13:32:e0:f9:33",
        "InitialConfiguration": "1",
        "AP_MAC": "BA:13:32:E0:F9:32",
        "date": "2025:10:27",
        "time": "15:50:18",
        "netstat": "2",
        "essid": "4445434F3547",
        "apcli0": "172.16.0.72",
        "eth0": "0.0.0.0",
        "eth2": "0.0.0.0",
        "ETH_MAC": "00:22:6C:24:8F:23",
        "ota_api_ver": "3.0",
        "mcu_ver_new": "0",
        "update_check_count": "2",
        "BleRemote_update_checked_counter": "0",
        "ra0": "10.10.10.254",
        "temp_uuid": "F1A6471ECC4E6F27",
        "cap1": "0x40000400",
        "capability": "0x20084808",
        "languages": "0x11ec",
        "prompt_status": "1",
        "alexa_ver": "20180604",
        "alexa_beta_enable": "0",
        "alexa_force_beta_cfg": "0",
        "ModuleColorNumber": "0",
        "ModuleColorString": "",
        "dsp_ver_new": "",
        "uboot_verinfo": "",
        "kernel_verinfo": "#1 SMP PREEMPT Wed Jul 9 10:57:58 CST 2025",
        "silence_ota_flag": "0",
        "ota_interface_ver": "2.0",
        "streams_all": "0xedf33fd",
        "streams": "0xedf33fd",
        "region": "unknown",
        "volume_control": "1",
        "external": "0x0",
        "plm_support": "0x700016",
        "mqtt_support": "1",
        "lbc_support": "0",
        "WifiChannel": "0",
        "RSSI": "-50",
        "BSSID": "**REDACTED**",
        "wlanSnr": "35",
        "wlanNoise": "-92",
        "wlanFreq": "5240",
        "wlanDataRate": "433",
        "battery": "0",
        "battery_percent": "0",
        "securemode": "1",
        "upnp_version": "1005",
        "upnp_uuid": "uuid:FF98F09C-F38D-A23D-1290-5F90FF98F09C",
        "uart_pass_port": "0",
        "communication_port": "8819",
        "web_firmware_update_hide": "0",
        "new_tunein_preset_and_alarm": "1",
        "new_iheart_podcast": "1",
        "tidal_version": "2.0",
        "service_version": "1.0",
        "HiFiSRC_version": "1.1",
        "EQ_support": "Eq4p_ver_2.0",
        "EQVersion": "4.3",
        "audio_channel_config": "1.0",
        "app_timezone_id": "Europe/London",
        "avs_timezone_id": "Europe/London",
        "tz_info_ver": "1.0",
        "tz": "1.0",
        "max_volume": "100",
        "power_mode": "-1",
        "security": "https/2.0",
        "security_version": "3.0",
        "security_capabilities": {
          "ver": "1.0",
          "aes_ver": "1.0"
        },
        "public_https_version": "1.0",
        "BleRemoteControl": "1",
        "BleRemoteConnected": "0",
        "BleRemoteException": "0",
        "autoSenseVersion": "1.0",
        "set_play_mode_enable": "0",
        "set_play_mode_gain": "0",
        "privacy_mode": "0",
        "GroupName": "WiiM Pro",
        "firmware_date": "20251009",
        "project": "WiiM_Pro_with_gc4a",
        "preset_slots": 12,
        "update_available": false
      }
    },
    "raw_coordinator_data": {
      "status_model": {
        "__type": "<class 'custom_components.wiim.models.PlayerStatus'>",
        "repr": "PlayerStatus(play_state='play', volume=100, mute=False, source='spotify', mode='31', position=16, seek=None, duration=333, title=\"Acceptable in the 80's\", artist='Calvin Harris', album='I Created Disco', entity_picture='https://i.scdn.co/image/ab67616d0000b273d0b33add0e39952e5e721226', cover_url='https://i.scdn.co/image/ab67616d0000b273d0b33add0e39952e5e721226', eq_preset='flat', wifi_rssi=None, wifi_channel=None, loop_mode=3, play_mode='repeat_one', repeat=None, shuffle=None, group=None, master_uuid=None, master_ip=None, uuid=None, type='0', ch='0', vendor='spotify:playlist:2DLPSGuAXEP3Vcsoovnru3', position_ms='16845', offset_pts='0', duration_ms='333680', title_hex='41636365707461626C6520696E207468652038302773', artist_hex='43616C76696E20486172726973', album_hex='49204372656174656420446973636F', alarmflag='0', plicount='0', plicurr='0', power=True, volume_level=1.0, position_updated_at=370799.537498825, audio_output={'hardware': '4', 'source': '0', 'audiocast': '0'})"
      },
      "device_model": {
        "__type": "<class 'custom_components.wiim.models.DeviceInfo'>",
        "repr": "DeviceInfo(uuid='FF98F09CF38DA23D12905F90', name='WiiM Pro', model='WiiM_Pro_with_gc4a', firmware='Linkplay.4.8.731953', mac='B8:13:32:E0:F9:32', ip=None, release_date='20251009', hardware='AmlogicA113', wmrm_version='4.3', mcu_ver='0', dsp_ver='', preset_key=12, group='0', master_uuid=None, master_ip=None, version_update='0', latest_version='0', language='en-GB', ssid='WiiM Pro-F932', hideSSID='0', build='release', priv_prj='WiiM_Pro_with_gc4a', project_build_name='WiiM_Pro_with_gc4a', FW_Release_version='', PCB_version='1', cast_enable=1, cast_usage_report=1, wmrm_sub_ver='7', expired='0', internet='1', BTMAC='b8:13:32:e0:f9:33', InitialConfiguration='1', AP_MAC='BA:13:32:E0:F9:32', date='2025:10:27', time='15:50:18', netstat='2', essid='4445434F3547', apcli0='172.16.0.72', eth0='0.0.0.0', eth2='0.0.0.0', ETH_MAC='00:22:6C:24:8F:23', ota_api_ver='3.0', mcu_ver_new='0', update_check_count='2', BleRemote_update_checked_counter='0', ra0='10.10.10.254', temp_uuid='F1A6471ECC4E6F27', cap1='0x40000400', capability='0x20084808', languages='0x11ec', prompt_status='1', alexa_ver='20180604', alexa_beta_enable='0', alexa_force_beta_cfg='0', ModuleColorNumber='0', ModuleColorString='', dsp_ver_new='', uboot_verinfo='', kernel_verinfo='#1 SMP PREEMPT Wed Jul 9 10:57:58 CST 2025', silence_ota_flag='0', ota_interface_ver='2.0', streams_all='0xedf33fd', streams='0xedf33fd', region='unknown', volume_control='1', external='0x0', plm_support='0x700016', mqtt_support='1', lbc_support='0', WifiChannel='0', RSSI='-50', BSSID='14:EB:B6:E0:7D:67', wlanSnr='35', wlanNoise='-92', wlanFreq='5240', wlanDataRate='433', battery='0', battery_percent='0', securemode='1', upnp_version='1005', upnp_uuid='uuid:FF98F09C-F38D-A23D-1290-5F90FF98F09C', uart_pass_port='0', communication_port='8819', web_firmware_update_hide='0', new_tunein_preset_and_alarm='1', new_iheart_podcast='1', tidal_version='2.0', service_version='1.0', HiFiSRC_version='1.1', EQ_support='Eq4p_ver_2.0', EQVersion='4.3', audio_channel_config='1.0', app_timezone_id='Europe/London', avs_timezone_id='Europe/London', tz_info_ver='1.0', tz='1.0', max_volume='100', power_mode='-1', security='https/2.0', security_version='3.0', security_capabilities={'ver': '1.0', 'aes_ver': '1.0'}, public_https_version='1.0', BleRemoteControl='1', BleRemoteConnected='0', BleRemoteException='0', autoSenseVersion='1.0', set_play_mode_enable='0', set_play_mode_gain='0', privacy_mode='0', GroupName='WiiM Pro', firmware_date='20251009', project='WiiM_Pro_with_gc4a', preset_slots=12, update_available=False)"
      },
      "multiroom": {
        "slaves": 0,
        "wmrm_version": "4.3",
        "surround": 0
      },
      "metadata_model": {
        "__type": "<class 'custom_components.wiim.models.TrackMetadata'>",
        "repr": "TrackMetadata(title=\"Acceptable in the 80's\", artist='Calvin Harris', album='I Created Disco', entity_picture='https://i.scdn.co/image/ab67616d0000b273d0b33add0e39952e5e721226', cover_url='https://i.scdn.co/image/ab67616d0000b273d0b33add0e39952e5e721226', sample_rate=44100, bit_depth=16, bit_rate=160, subtitle='unknow', albumArtURI='https://i.scdn.co/image/ab67616d0000b273d0b33add0e39952e5e721226', sampleRate='44100', bitDepth='16', bitRate='160', trackId='00cxhG668jV6gU6VK2FUVI')"
      },
      "metadata": {
        "title": "Acceptable in the 80's",
        "artist": "Calvin Harris",
        "album": "I Created Disco",
        "entity_picture": "https://i.scdn.co/image/ab67616d0000b273d0b33add0e39952e5e721226",
        "cover_url": "https://i.scdn.co/image/ab67616d0000b273d0b33add0e39952e5e721226",
        "sample_rate": 44100,
        "bit_depth": 16,
        "bit_rate": 160,
        "subtitle": "unknow",
        "albumArtURI": "https://i.scdn.co/image/ab67616d0000b273d0b33add0e39952e5e721226",
        "sampleRate": "44100",
        "bitDepth": "16",
        "bitRate": "160",
        "trackId": "00cxhG668jV6gU6VK2FUVI"
      },
      "eq_model": {
        "__type": "<class 'custom_components.wiim.models.EQInfo'>",
        "repr": "EQInfo(eq_enabled=False, eq_preset=None)"
      },
      "eq": {
        "eq_enabled": false
      },
      "presets": [],
      "role": "solo",
      "polling_metrics": {
        "__type": "<class 'custom_components.wiim.models.PollingMetrics'>",
        "repr": "PollingMetrics(interval=1.0, is_playing=True, api_capabilities={'statusex_supported': None, 'metadata_supported': True, 'eq_supported': True})"
      },
      "polling": {
        "interval": 1.0,
        "is_playing": true,
        "api_capabilities": {
          "statusex_supported": null,
          "metadata_supported": true,
          "eq_supported": true
        },
        "adaptive_polling": true,
        "interval_reason": "playback_active",
        "fast_polling_active": true,
        "last_device_info_check": 1761580218.8163807,
        "last_multiroom_check": 1761580251.8174496
      },
      "audio_output": null
    }
  },
  "issues": []
}

**Comment by mjcumming** [comment]
0.2.1 should fix this ...

**Comment by Select446** [comment]
Sorry for the late response, i've tried the latest version but the issue still persists:

In each test i load up the wiim iphone app, start Spotify, pair bluetooth, return to the integration, change the output to something different and then change it back to bluetooth. I've noted that if i turn off the wiim pro (via socket) while its connected to bluetooth and then switch it back later it will automatically connect back to the bluetooth speaker without requiring any pairing in the app

[wiim_2025-11-01T18-24-24.377Z.log](https://github.com/user-attachments/files/23286212/wiim_2025-11-01T18-24-24.377Z.log)

{
  "home_assistant": {
    "installation_type": "Home Assistant Container",
    "version": "2025.10.4",
    "dev": false,
    "hassio": false,
    "virtualenv": false,
    "python_version": "3.13.7",
    "docker": true,
    "arch": "aarch64",
    "timezone": "Europe/London",
    "os_name": "Linux",
    "os_version": "6.1.21-v8+",
    "container_arch": "armv7",
    "run_as_root": true
  },
  "custom_components": {
    "monitor_docker": {
      "documentation": "https://github.com/ualex73/monitor_docker",
      "version": "1.18",
      "requirements": [
        "aiodocker==0.22.0",
        "python-dateutil==2.9.0"
      ]
    },
    "teamtracker": {
      "documentation": "https://github.com/vasqued2/ha-teamtracker",
      "version": "0.1",
      "requirements": [
        "arrow",
        "aiofiles"
      ]
    },
    "advanced_snapshot": {
      "documentation": "https://github.com/Phil7989/advanced_snapshot",
      "version": "2025.2.3.1",
      "requirements": [
        "Pillow",
        "ffmpeg-python"
      ]
    },
    "wiim": {
      "documentation": "https://github.com/mjcumming/wiim",
      "version": "0.2.11",
      "requirements": []
    },
    "spotcast": {
      "documentation": "https://github.com/fondberg/spotcast",
      "version": "v4.0.1",
      "requirements": [
        "spotipy==2.23.0"
      ]
    },
    "localtuya": {
      "documentation": "https://github.com/xZetsubou/hass-localtuya/",
      "version": "2025.10.0",
      "requirements": []
    },
    "plant": {
      "documentation": "https://github.com/Olen/homeassistant-plant/",
      "version": "2025.8.0",
      "requirements": [
        "async-timeout>=4.0.2"
      ]
    },
    "dreo": {
      "documentation": "https://github.com/jeffsteinbok/hass-dreo/blob/master/README.md",
      "version": "1.4.1",
      "requirements": [
        "websockets"
      ]
    },
    "bose": {
      "documentation": "https://github.com/cavefire/Bose-Homeassistant",
      "version": "1.0.2",
      "requirements": [
        "pybose==2025.8.1"
      ]
    },
    "remote_homeassistant": {
      "documentation": "https://github.com/custom-components/remote_homeassistant",
      "version": "4.5",
      "requirements": []
    },
    "watchman": {
      "documentation": "https://github.com/dummylabs/thewatchman",
      "version": "0.6.5",
      "requirements": [
        "prettytable==3.12.0"
      ]
    },
    "network_scanner": {
      "documentation": "https://github.com/parvez/network_scanner",
      "version": "1.0.7",
      "requirements": [
        "python-nmap"
      ]
    },
    "openai_stt": {
      "documentation": "https://github.com/einToast/openai_stt_ha",
      "version": "1.2.0",
      "requirements": []
    },
    "skyq": {
      "documentation": "https://github.com/RogerSelwyn/Home_Assistant_SkyQ_MediaPlayer",
      "version": "v2.13.1",
      "requirements": [
        "pyskyqremote==0.3.26"
      ]
    },
    "alexa_media": {
      "documentation": "https://github.com/alandtse/alexa_media_player/wiki",
      "version": "5.7.9",
      "requirements": [
        "alexapy==1.29.8",
        "packaging>=20.3",
        "wrapt>=1.14.0"
      ]
    },
    "hpprinter": {
      "documentation": "https://github.com/elad-bar/ha-hpprinter",
      "version": "2.0.5",
      "requirements": [
        "xmltodict~=0.13.0",
        "flatten_json",
        "defusedxml"
      ]
    },
    "hacs": {
      "documentation": "https://hacs.xyz/docs/use/",
      "version": "2.0.5",
      "requirements": [
        "aiogithubapi>=22.10.1"
      ]
    },
    "meross_lan": {
      "documentation": "https://github.com/krahabb/meross_lan",
      "version": "5.6.0",
      "requirements": []
    },
    "xiaomi_miot": {
      "documentation": "https://github.com/al-one/hass-xiaomi-miot",
      "version": "1.1.0",
      "requirements": [
        "construct>=2.10.68",
        "python-miio>=0.5.12",
        "micloud>=0.5"
      ]
    },
    "tplink_router": {
      "documentation": "https://github.com/AlexandrErohin/home-assistant-tplink-router",
      "version": "v2.12.2",
      "requirements": [
        "tplinkrouterc6u==5.10.2"
      ]
    },
    "attribute_as_sensor": {
      "documentation": "https://github.com/gjohansson-ST/attribute_as_sensor/blob/master/readme.md",
      "version": "1.6",
      "requirements": []
    },
    "media_player_template": {
      "documentation": "https://github.com/Sennevds/media_player.template",
      "version": "1.0.2",
      "requirements": []
    },
    "hon": {
      "documentation": "https://github.com/gvigroux/hon",
      "version": "0.7.16",
      "requirements": []
    },
    "dash_cast": {
      "documentation": "https://github.com/AlexxIT/DashCast",
      "version": "1.1.1",
      "requirements": []
    },
    "nest_protect": {
      "documentation": "https://github.com/imicknl/ha-nest-protect",
      "version": "0.4.1",
      "requirements": []
    },
    "config_editor": {
      "documentation": "https://github.com/junkfix/config-editor-card",
      "version": "5.0.0",
      "requirements": []
    },
    "waveshare_ups_hat": {
      "documentation": "https://github.com/mykhailog/hacs_waveshare_ups_hat",
      "version": "0.1.6",
      "requirements": [
        "smbus2>=0.4.2"
      ]
    },
    "pyscript": {
      "documentation": "https://github.com/custom-components/pyscript",
      "version": "1.6.4",
      "requirements": [
        "croniter==6.0.0",
        "watchdog==6.0.0"
      ]
    },
    "average": {
      "documentation": "https://github.com/Limych/ha-average",
      "version": "2.4.0",
      "requirements": [
        "pip>=21.3.1"
      ]
    },
    "ttlock": {
      "documentation": "https://github.com/jbergler/hass-ttlock",
      "version": "v0.7.2",
      "requirements": [
        "pydantic"
      ]
    }
  },
  "integration_manifest": {
    "domain": "wiim",
    "name": "WiiM",
    "codeowners": [
      "mjcumming"
    ],
    "config_flow": true,
    "dependencies": [],
    "documentation": "https://github.com/mjcumming/wiim",
    "integration_type": "device",
    "iot_class": "local_polling",
    "issue_tracker": "https://github.com/mjcumming/wiim/issues",
    "quality_scale": "silver",
    "requirements": [],
    "ssdp": [
      {
        "manufacturer": "WiiM",
        "st": "upnp:rootdevice"
      },
      {
        "manufacturer": "LinkPlay",
        "st": "upnp:rootdevice"
      },
      {
        "manufacturer": "WiiM",
        "device_type": "urn:schemas-upnp-org:device:MediaRenderer:1"
      },
      {
        "manufacturer": "LinkPlay",
        "device_type": "urn:schemas-upnp-org:device:MediaRenderer:1"
      },
      {
        "st": "urn:schemas-upnp-org:service:AVTransport:1"
      },
      {
        "st": "urn:schemas-upnp-org:service:RenderingControl:1"
      },
      {
        "st": "urn:schemas-upnp-org:service:ConnectionManager:1"
      }
    ],
    "version": "0.2.11",
    "zeroconf": [
      {
        "type": "_linkplay._tcp.local."
      }
    ],
    "is_built_in": false,
    "overwrites_built_in": false
  },
  "setup_times": {
    "null": {
      "setup": 6.357405800372362e-05
    },
    "01K8V5PGVVRSEAETM4V7MYB0F1": {
      "config_entry_setup": 40.26771608903073
    }
  },
  "data": {
    "device_info": {
      "speaker_uuid": "FF98F09CF38DA23D12905F90",
      "name": "WiiM Pro",
      "model": "WiiM_Pro_with_gc4a",
      "firmware": "Linkplay.4.8.731953",
      "role": "solo",
      "available": true,
      "ip_address": {
        "ip": "**REDACTED**"
      },
      "mac_address": {
        "mac": "**REDACTED**"
      }
    },
    "group_info": {
      "role": "solo",
      "is_group_coordinator": false,
      "group_members_count": 0,
      "group_member_names": [],
      "coordinator_name": null
    },
    "media_info": {
      "playback_state": "playing",
      "volume_level": 1.0,
      "is_muted": false,
      "current_source": "Spotify",
      "media_title": "Flashback",
      "media_artist": "Calvin Harris",
      "media_album": "Ready For The Weekend",
      "media_duration": 227,
      "media_position": 144,
      "media_image_url": "https://i.scdn.co/image/ab67616d0000b27300d6698dffdf81ce656dd26f",
      "shuffle_state": false,
      "repeat_mode": "one",
      "sound_mode": "Flat"
    },
    "api_capabilities": {
      "metadata_supported": true,
      "statusex_supported": null,
      "eq_supported": true,
      "presets_supported": false
    },
    "upnp_status": {
      "status": "Not Active",
      "status_detail": "Not Initialized (Likely disabled)",
      "enabled": true,
      "subscription_failed": false,
      "event_count": 0,
      "last_notify": null,
      "has_upnp_client": false,
      "has_upnp_eventer": false,
      "fallback_mode": "HTTP Polling"
    },
    "api_status": {
      "host": "**REDACTED**",
      "timeout": 2.0,
      "client_type": "<class 'custom_components.wiim.api.WiiMClient'>"
    },
    "model_data": {
      "status_model": {
        "play_state": "play",
        "volume": 100,
        "mute": false,
        "source": "spotify",
        "mode": "31",
        "position": 144,
        "duration": 227,
        "title": "Flashback",
        "artist": "Calvin Harris",
        "album": "Ready For The Weekend",
        "entity_picture": "https://i.scdn.co/image/ab67616d0000b27300d6698dffdf81ce656dd26f",
        "cover_url": "https://i.scdn.co/image/ab67616d0000b27300d6698dffdf81ce656dd26f",
        "eq_preset": "flat",
        "loop_mode": 3,
        "play_mode": "repeat_one",
        "type": "0",
        "ch": "0",
        "vendor": "spotify:playlist:2DLPSGuAXEP3Vcsoovnru3",
        "position_ms": "144767",
        "offset_pts": "0",
        "duration_ms": "227880",
        "title_hex": "466C6173686261636B",
        "artist_hex": "43616C76696E20486172726973",
        "album_hex": "526561647920466F7220546865205765656B656E64",
        "alarmflag": "0",
        "plicount": "0",
        "plicurr": "0",
        "power": true,
        "volume_level": 1.0,
        "position_updated_at": 811983.285248811,
        "audio_output": {
          "hardware": "4",
          "source": "0",
          "audiocast": "0"
        }
      },
      "device_model": {
        "uuid": "**REDACTED**",
        "name": "WiiM Pro",
        "model": "WiiM_Pro_with_gc4a",
        "firmware": "Linkplay.4.8.731953",
        "mac": "B8:13:32:E0:F9:32",
        "release_date": "20251009",
        "hardware": "AmlogicA113",
        "wmrm_version": "4.3",
        "mcu_ver": "0",
        "dsp_ver": "",
        "preset_key": 12,
        "group": "0",
        "version_update": "0",
        "latest_version": "0",
        "language": "en-GB",
        "ssid": "**REDACTED**",
        "hideSSID": "0",
        "build": "release",
        "priv_prj": "WiiM_Pro_with_gc4a",
        "project_build_name": "WiiM_Pro_with_gc4a",
        "FW_Release_version": "",
        "PCB_version": "1",
        "cast_enable": 1,
        "cast_usage_report": 1,
        "wmrm_sub_ver": "7",
        "expired": "0",
        "internet": "1",
        "BTMAC": "b8:13:32:e0:f9:33",
        "InitialConfiguration": "1",
        "AP_MAC": "BA:13:32:E0:F9:32",
        "date": "2025:11:01",
        "time": "18:23:48",
        "netstat": "2",
        "essid": "4445434F3547",
        "apcli0": "172.16.0.84",
        "eth0": "0.0.0.0",
        "eth2": "0.0.0.0",
        "ETH_MAC": "00:22:6C:24:8F:23",
        "ota_api_ver": "3.0",
        "mcu_ver_new": "0",
        "update_check_count": "2",
        "BleRemote_update_checked_counter": "0",
        "ra0": "10.10.10.254",
        "temp_uuid": "1F9CBBB4C453BF2A",
        "cap1": "0x40000400",
        "capability": "0x20084808",
        "languages": "0x11ec",
        "prompt_status": "1",
        "alexa_ver": "20180604",
        "alexa_beta_enable": "0",
        "alexa_force_beta_cfg": "0",
        "ModuleColorNumber": "0",
        "ModuleColorString": "",
        "dsp_ver_new": "",
        "uboot_verinfo": "",
        "kernel_verinfo": "#1 SMP PREEMPT Wed Jul 9 10:57:58 CST 2025",
        "silence_ota_flag": "0",
        "ota_interface_ver": "2.0",
        "streams_all": "0xedf33fd",
        "streams": "0xedf33fd",
        "region": "unknown",
        "volume_control": "1",
        "external": "0x0",
        "plm_support": "0x700016",
        "mqtt_support": "1",
        "lbc_support": "0",
        "WifiChannel": "0",
        "RSSI": "-46",
        "BSSID": "**REDACTED**",
        "wlanSnr": "35",
        "wlanNoise": "-91",
        "wlanFreq": "5240",
        "wlanDataRate": "433",
        "battery": "0",
        "battery_percent": "0",
        "securemode": "1",
        "upnp_version": "1005",
        "upnp_uuid": "uuid:FF98F09C-F38D-A23D-1290-5F90FF98F09C",
        "uart_pass_port": "0",
        "communication_port": "8819",
        "web_firmware_update_hide": "0",
        "new_tunein_preset_and_alarm": "1",
        "new_iheart_podcast": "1",
        "tidal_version": "2.0",
        "service_version": "1.0",
        "HiFiSRC_version": "1.1",
        "EQ_support": "Eq4p_ver_2.0",
        "EQVersion": "4.3",
        "audio_channel_config": "1.0",
        "app_timezone_id": "Europe/London",
        "avs_timezone_id": "Europe/London",
        "tz_info_ver": "1.0",
        "tz": "1.0",
        "max_volume": "100",
        "power_mode": "-1",
        "security": "https/2.0",
        "security_version": "3.0",
        "security_capabilities": {
          "ver": "1.0",
          "aes_ver": "1.0"
        },
        "public_https_version": "1.0",
        "BleRemoteControl": "1",
        "BleRemoteConnected": "0",
        "BleRemoteException": "0",
        "autoSenseVersion": "1.0",
        "set_play_mode_enable": "0",
        "set_play_mode_gain": "0",
        "privacy_mode": "0",
        "GroupName": "WiiM Pro",
        "firmware_date": "20251009",
        "project": "WiiM_Pro_with_gc4a",
        "preset_slots": 12,
        "update_available": false
      }
    },
    "raw_coordinator_data": {
      "status_model": {
        "__type": "<class 'custom_components.wiim.models.PlayerStatus'>",
        "repr": "PlayerStatus(play_state='play', volume=100, mute=False, source='spotify', mode='31', position=144, seek=None, duration=227, title='Flashback', artist='Calvin Harris', album='Ready For The Weekend', entity_picture='https://i.scdn.co/image/ab67616d0000b27300d6698dffdf81ce656dd26f', cover_url='https://i.scdn.co/image/ab67616d0000b27300d6698dffdf81ce656dd26f', eq_preset='flat', wifi_rssi=None, wifi_channel=None, loop_mode=3, play_mode='repeat_one', repeat=None, shuffle=None, group=None, master_uuid=None, master_ip=None, uuid=None, type='0', ch='0', vendor='spotify:playlist:2DLPSGuAXEP3Vcsoovnru3', position_ms='144767', offset_pts='0', duration_ms='227880', title_hex='466C6173686261636B', artist_hex='43616C76696E20486172726973', album_hex='526561647920466F7220546865205765656B656E64', alarmflag='0', plicount='0', plicurr='0', power=True, volume_level=1.0, position_updated_at=811983.285248811, audio_output={'hardware': '4', 'source': '0', 'audiocast': '0'})"
      },
      "device_model": {
        "__type": "<class 'custom_components.wiim.models.DeviceInfo'>",
        "repr": "DeviceInfo(uuid='FF98F09CF38DA23D12905F90', name='WiiM Pro', model='WiiM_Pro_with_gc4a', firmware='Linkplay.4.8.731953', mac='B8:13:32:E0:F9:32', ip=None, release_date='20251009', hardware='AmlogicA113', wmrm_version='4.3', mcu_ver='0', dsp_ver='', preset_key=12, group='0', master_uuid=None, master_ip=None, version_update='0', latest_version='0', language='en-GB', ssid='WiiM Pro-F932', hideSSID='0', build='release', priv_prj='WiiM_Pro_with_gc4a', project_build_name='WiiM_Pro_with_gc4a', FW_Release_version='', PCB_version='1', cast_enable=1, cast_usage_report=1, wmrm_sub_ver='7', expired='0', internet='1', BTMAC='b8:13:32:e0:f9:33', InitialConfiguration='1', AP_MAC='BA:13:32:E0:F9:32', date='2025:11:01', time='18:23:48', netstat='2', essid='4445434F3547', apcli0='172.16.0.84', eth0='0.0.0.0', eth2='0.0.0.0', ETH_MAC='00:22:6C:24:8F:23', ota_api_ver='3.0', mcu_ver_new='0', update_check_count='2', BleRemote_update_checked_counter='0', ra0='10.10.10.254', temp_uuid='1F9CBBB4C453BF2A', cap1='0x40000400', capability='0x20084808', languages='0x11ec', prompt_status='1', alexa_ver='20180604', alexa_beta_enable='0', alexa_force_beta_cfg='0', ModuleColorNumber='0', ModuleColorString='', dsp_ver_new='', uboot_verinfo='', kernel_verinfo='#1 SMP PREEMPT Wed Jul 9 10:57:58 CST 2025', silence_ota_flag='0', ota_interface_ver='2.0', streams_all='0xedf33fd', streams='0xedf33fd', region='unknown', volume_control='1', external='0x0', plm_support='0x700016', mqtt_support='1', lbc_support='0', WifiChannel='0', RSSI='-46', BSSID='14:EB:B6:E0:7D:67', wlanSnr='35', wlanNoise='-91', wlanFreq='5240', wlanDataRate='433', battery='0', battery_percent='0', securemode='1', upnp_version='1005', upnp_uuid='uuid:FF98F09C-F38D-A23D-1290-5F90FF98F09C', uart_pass_port='0', communication_port='8819', web_firmware_update_hide='0', new_tunein_preset_and_alarm='1', new_iheart_podcast='1', tidal_version='2.0', service_version='1.0', HiFiSRC_version='1.1', EQ_support='Eq4p_ver_2.0', EQVersion='4.3', audio_channel_config='1.0', app_timezone_id='Europe/London', avs_timezone_id='Europe/London', tz_info_ver='1.0', tz='1.0', max_volume='100', power_mode='-1', security='https/2.0', security_version='3.0', security_capabilities={'ver': '1.0', 'aes_ver': '1.0'}, public_https_version='1.0', BleRemoteControl='1', BleRemoteConnected='0', BleRemoteException='0', autoSenseVersion='1.0', set_play_mode_enable='0', set_play_mode_gain='0', privacy_mode='0', GroupName='WiiM Pro', firmware_date='20251009', project='WiiM_Pro_with_gc4a', preset_slots=12, update_available=False)"
      },
      "multiroom": {
        "slaves": 0,
        "wmrm_version": "4.3",
        "surround": 0
      },
      "metadata_model": {
        "__type": "<class 'custom_components.wiim.models.TrackMetadata'>",
        "repr": "TrackMetadata(title='Flashback', artist='Calvin Harris', album='Ready For The Weekend', entity_picture='https://i.scdn.co/image/ab67616d0000b27300d6698dffdf81ce656dd26f', cover_url='https://i.scdn.co/image/ab67616d0000b27300d6698dffdf81ce656dd26f', sample_rate=44100, bit_depth=16, bit_rate=160, subtitle='unknow', albumArtURI='https://i.scdn.co/image/ab67616d0000b27300d6698dffdf81ce656dd26f', sampleRate='44100', bitDepth='16', bitRate='160', trackId='6A8llSO9QFF4djCCmuCrNu')"
      },
      "metadata": {
        "title": "Flashback",
        "artist": "Calvin Harris",
        "album": "Ready For The Weekend",
        "entity_picture": "https://i.scdn.co/image/ab67616d0000b27300d6698dffdf81ce656dd26f",
        "cover_url": "https://i.scdn.co/image/ab67616d0000b27300d6698dffdf81ce656dd26f",
        "sample_rate": 44100,
        "bit_depth": 16,
        "bit_rate": 160,
        "subtitle": "unknow",
        "albumArtURI": "https://i.scdn.co/image/ab67616d0000b27300d6698dffdf81ce656dd26f",
        "sampleRate": "44100",
        "bitDepth": "16",
        "bitRate": "160",
        "trackId": "6A8llSO9QFF4djCCmuCrNu"
      },
      "eq_model": {
        "__type": "<class 'custom_components.wiim.models.EQInfo'>",
        "repr": "EQInfo(eq_enabled=False, eq_preset=None)"
      },
      "eq": {
        "eq_enabled": false
      },
      "presets": [],
      "role": "solo",
      "polling_metrics": {
        "__type": "<class 'custom_components.wiim.models.PollingMetrics'>",
        "repr": "PollingMetrics(interval=1.0, is_playing=True, api_capabilities={'statusex_supported': None, 'metadata_supported': True, 'eq_supported': True})"
      },
      "polling": {
        "interval": 1.0,
        "is_playing": true,
        "api_capabilities": {
          "statusex_supported": null,
          "metadata_supported": true,
          "eq_supported": true
        },
        "adaptive_polling": true,
        "interval_reason": "playback_active",
        "fast_polling_active": true,
        "last_device_info_check": 1762021428.569686,
        "last_multiroom_check": 1762021425.5793397
      },
      "audio_output": null
    }
  },
  "issues": []
}

**Comment by mjcumming** [comment]
ok, the latest release should fix this - in the outputs dropdown - all paired BT devices should be listed - devices must be paired via the WiiM app - let me know it works for you.

**Comment by Select446** [comment]
It works! Fantastic work and persistence on this one - much appreciated - is there any way of supporting you? 

![image](https://github.com/user-attachments/assets/f226a71f-b316-4817-9e75-09cdb33d2e96)

**Comment by mjcumming** [comment]
Sweet! Just give the repo a Star and a shoutout. Thanks.,
